image: eclipse-temurin:17-jdk

before_script:
  - env | grep -i PROXY
  - apt-get update -y
  - apt-get install -y make wget
  - echo -e 'systemProp.http.proxyHost=proxy-serveur.univ-nantes.prive\nsystemProp.http.proxyPort=3128\nsystemProp.https.proxyHost=proxy-serveur.univ-nantes.prive\nsystemProp.https.proxyPort=3128' >  gradle.properties


stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job will compile your project
  stage: build
  script:
    - chmod +x gradlew   # Give permission to execute the Gradle wrapper script
    - make     # Assuming 'make' is your command to build the project

test-job:        # This job will run tests on your project
  stage: test
  script:
    - make test   # Runs any tests for your project
