image: eclipse-temurin:17-jdk

before_script:
  - hostname
  - env | grep -i PROXY
  - apt-get update -y
  - apt-get install -y make wget libxml2-utils
  - echo -e 'systemProp.http.proxyHost=proxy-serveur.univ-nantes.prive\nsystemProp.http.proxyPort=3128\nsystemProp.https.proxyHost=proxy-serveur.univ-nantes.prive\nsystemProp.https.proxyPort=3128' >  gradle.properties


stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - apptainer

build-job:       # This job will compile your project
  stage: build
  script:
    - chmod +x gradlew   # Give permission to execute the Gradle wrapper script
    - make     # Assuming 'make' is your command to build the project
    - xmllint --noout --stream src/main/resources/so/so-simple.owl
  artifacts:
    path:
        - dist/jvarkit.jar

test-job:        # This job will run tests on your project
  stage: test
  script:
    - make test JAVA_PROXY="-Dhttp.proxyHost=proxy-serveur.univ-nantes.prive -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy-serveur.univ-nantes.prive -Dhttps.proxyPort=3128"

apptainer-job:
  stage: apptainer
  script:
    - apt install -y software-properties-common
    - add-apt-repository -y ppa:apptainer/ppa
    - apt update
    - apt install -y apptainer
