#!/bin/bash
set -x
java -DenableExternalEntityProcessing=true \
	-cp lib/com/sun/xml/dtd-parser/dtd-parser/1.5.1/dtd-parser-1.5.1.jar:lib/org/glassfish/jaxb/jaxb-runtime/4.0.5/jaxb-runtime-4.0.5.jar:lib/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar:./lib/org/glassfish/jaxb/jaxb-core/4.0.5/jaxb-core-4.0.5.jar:./lib/org/glassfish/jaxb/jaxb-xjc/4.0.5/jaxb-xjc-4.0.5.jar:./lib/org/glassfish/jaxb/codemodel/4.0.5/codemodel-4.0.5.jar:./lib/com/sun/istack/istack-commons-runtime/4.2.0/istack-commons-runtime-4.2.0.jar:./lib/org/glassfish/jaxb/xsom/4.0.5/xsom-4.0.5.jar:./lib/com/sun/xml/bind/external/rngom/4.0.5/rngom-4.0.5.jar:lib/com/sun/xml/bind/external/relaxng-datatype/4.0.5/relaxng-datatype-4.0.5.jar:./lib/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar  com.sun.tools.xjc.XJCFacade \
	$@
