//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.uniprot.schema;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.lindenb.jvarkit.uniprot.schema package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Copyright_QNAME = new QName("http://uniprot.org/uniprot", "copyright");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.lindenb.jvarkit.uniprot.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IsoformType }
     * 
     * @return
     *     the new instance of {@link IsoformType }
     */
    public IsoformType createIsoformType() {
        return new IsoformType();
    }

    /**
     * Create an instance of {@link SourceDataType }
     * 
     * @return
     *     the new instance of {@link SourceDataType }
     */
    public SourceDataType createSourceDataType() {
        return new SourceDataType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     * @return
     *     the new instance of {@link CommentType }
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link CommentType.Conflict }
     * 
     * @return
     *     the new instance of {@link CommentType.Conflict }
     */
    public CommentType.Conflict createCommentTypeConflict() {
        return new CommentType.Conflict();
    }

    /**
     * Create an instance of {@link OrganismType }
     * 
     * @return
     *     the new instance of {@link OrganismType }
     */
    public OrganismType createOrganismType() {
        return new OrganismType();
    }

    /**
     * Create an instance of {@link ProteinType }
     * 
     * @return
     *     the new instance of {@link ProteinType }
     */
    public ProteinType createProteinType() {
        return new ProteinType();
    }

    /**
     * Create an instance of {@link Uniprot }
     * 
     * @return
     *     the new instance of {@link Uniprot }
     */
    public Uniprot createUniprot() {
        return new Uniprot();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     * @return
     *     the new instance of {@link Entry }
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link GeneType }
     * 
     * @return
     *     the new instance of {@link GeneType }
     */
    public GeneType createGeneType() {
        return new GeneType();
    }

    /**
     * Create an instance of {@link GeneLocationType }
     * 
     * @return
     *     the new instance of {@link GeneLocationType }
     */
    public GeneLocationType createGeneLocationType() {
        return new GeneLocationType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     * @return
     *     the new instance of {@link ReferenceType }
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link DbReferenceType }
     * 
     * @return
     *     the new instance of {@link DbReferenceType }
     */
    public DbReferenceType createDbReferenceType() {
        return new DbReferenceType();
    }

    /**
     * Create an instance of {@link ProteinExistenceType }
     * 
     * @return
     *     the new instance of {@link ProteinExistenceType }
     */
    public ProteinExistenceType createProteinExistenceType() {
        return new ProteinExistenceType();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     * @return
     *     the new instance of {@link KeywordType }
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     * @return
     *     the new instance of {@link FeatureType }
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link EvidenceType }
     * 
     * @return
     *     the new instance of {@link EvidenceType }
     */
    public EvidenceType createEvidenceType() {
        return new EvidenceType();
    }

    /**
     * Create an instance of {@link SequenceType }
     * 
     * @return
     *     the new instance of {@link SequenceType }
     */
    public SequenceType createSequenceType() {
        return new SequenceType();
    }

    /**
     * Create an instance of {@link GeneNameType }
     * 
     * @return
     *     the new instance of {@link GeneNameType }
     */
    public GeneNameType createGeneNameType() {
        return new GeneNameType();
    }

    /**
     * Create an instance of {@link OrganismNameType }
     * 
     * @return
     *     the new instance of {@link OrganismNameType }
     */
    public OrganismNameType createOrganismNameType() {
        return new OrganismNameType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     * @return
     *     the new instance of {@link StatusType }
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link CitationType }
     * 
     * @return
     *     the new instance of {@link CitationType }
     */
    public CitationType createCitationType() {
        return new CitationType();
    }

    /**
     * Create an instance of {@link ConsortiumType }
     * 
     * @return
     *     the new instance of {@link ConsortiumType }
     */
    public ConsortiumType createConsortiumType() {
        return new ConsortiumType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     * @return
     *     the new instance of {@link PersonType }
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link NameListType }
     * 
     * @return
     *     the new instance of {@link NameListType }
     */
    public NameListType createNameListType() {
        return new NameListType();
    }

    /**
     * Create an instance of {@link ReactionType }
     * 
     * @return
     *     the new instance of {@link ReactionType }
     */
    public ReactionType createReactionType() {
        return new ReactionType();
    }

    /**
     * Create an instance of {@link PhysiologicalReactionType }
     * 
     * @return
     *     the new instance of {@link PhysiologicalReactionType }
     */
    public PhysiologicalReactionType createPhysiologicalReactionType() {
        return new PhysiologicalReactionType();
    }

    /**
     * Create an instance of {@link CofactorType }
     * 
     * @return
     *     the new instance of {@link CofactorType }
     */
    public CofactorType createCofactorType() {
        return new CofactorType();
    }

    /**
     * Create an instance of {@link SubcellularLocationType }
     * 
     * @return
     *     the new instance of {@link SubcellularLocationType }
     */
    public SubcellularLocationType createSubcellularLocationType() {
        return new SubcellularLocationType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     * @return
     *     the new instance of {@link EventType }
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link InteractantType }
     * 
     * @return
     *     the new instance of {@link InteractantType }
     */
    public InteractantType createInteractantType() {
        return new InteractantType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     * @return
     *     the new instance of {@link PropertyType }
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     * @return
     *     the new instance of {@link LocationType }
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     * @return
     *     the new instance of {@link PositionType }
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link LigandType }
     * 
     * @return
     *     the new instance of {@link LigandType }
     */
    public LigandType createLigandType() {
        return new LigandType();
    }

    /**
     * Create an instance of {@link LigandPartType }
     * 
     * @return
     *     the new instance of {@link LigandPartType }
     */
    public LigandPartType createLigandPartType() {
        return new LigandPartType();
    }

    /**
     * Create an instance of {@link MoleculeType }
     * 
     * @return
     *     the new instance of {@link MoleculeType }
     */
    public MoleculeType createMoleculeType() {
        return new MoleculeType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     * @return
     *     the new instance of {@link SourceType }
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link ImportedFromType }
     * 
     * @return
     *     the new instance of {@link ImportedFromType }
     */
    public ImportedFromType createImportedFromType() {
        return new ImportedFromType();
    }

    /**
     * Create an instance of {@link EvidencedStringType }
     * 
     * @return
     *     the new instance of {@link EvidencedStringType }
     */
    public EvidencedStringType createEvidencedStringType() {
        return new EvidencedStringType();
    }

    /**
     * Create an instance of {@link IsoformType.Name }
     * 
     * @return
     *     the new instance of {@link IsoformType.Name }
     */
    public IsoformType.Name createIsoformTypeName() {
        return new IsoformType.Name();
    }

    /**
     * Create an instance of {@link IsoformType.Sequence }
     * 
     * @return
     *     the new instance of {@link IsoformType.Sequence }
     */
    public IsoformType.Sequence createIsoformTypeSequence() {
        return new IsoformType.Sequence();
    }

    /**
     * Create an instance of {@link SourceDataType.Strain }
     * 
     * @return
     *     the new instance of {@link SourceDataType.Strain }
     */
    public SourceDataType.Strain createSourceDataTypeStrain() {
        return new SourceDataType.Strain();
    }

    /**
     * Create an instance of {@link SourceDataType.Plasmid }
     * 
     * @return
     *     the new instance of {@link SourceDataType.Plasmid }
     */
    public SourceDataType.Plasmid createSourceDataTypePlasmid() {
        return new SourceDataType.Plasmid();
    }

    /**
     * Create an instance of {@link SourceDataType.Transposon }
     * 
     * @return
     *     the new instance of {@link SourceDataType.Transposon }
     */
    public SourceDataType.Transposon createSourceDataTypeTransposon() {
        return new SourceDataType.Transposon();
    }

    /**
     * Create an instance of {@link SourceDataType.Tissue }
     * 
     * @return
     *     the new instance of {@link SourceDataType.Tissue }
     */
    public SourceDataType.Tissue createSourceDataTypeTissue() {
        return new SourceDataType.Tissue();
    }

    /**
     * Create an instance of {@link CommentType.Absorption }
     * 
     * @return
     *     the new instance of {@link CommentType.Absorption }
     */
    public CommentType.Absorption createCommentTypeAbsorption() {
        return new CommentType.Absorption();
    }

    /**
     * Create an instance of {@link CommentType.Kinetics }
     * 
     * @return
     *     the new instance of {@link CommentType.Kinetics }
     */
    public CommentType.Kinetics createCommentTypeKinetics() {
        return new CommentType.Kinetics();
    }

    /**
     * Create an instance of {@link CommentType.PhDependence }
     * 
     * @return
     *     the new instance of {@link CommentType.PhDependence }
     */
    public CommentType.PhDependence createCommentTypePhDependence() {
        return new CommentType.PhDependence();
    }

    /**
     * Create an instance of {@link CommentType.RedoxPotential }
     * 
     * @return
     *     the new instance of {@link CommentType.RedoxPotential }
     */
    public CommentType.RedoxPotential createCommentTypeRedoxPotential() {
        return new CommentType.RedoxPotential();
    }

    /**
     * Create an instance of {@link CommentType.TemperatureDependence }
     * 
     * @return
     *     the new instance of {@link CommentType.TemperatureDependence }
     */
    public CommentType.TemperatureDependence createCommentTypeTemperatureDependence() {
        return new CommentType.TemperatureDependence();
    }

    /**
     * Create an instance of {@link CommentType.Link }
     * 
     * @return
     *     the new instance of {@link CommentType.Link }
     */
    public CommentType.Link createCommentTypeLink() {
        return new CommentType.Link();
    }

    /**
     * Create an instance of {@link CommentType.Disease }
     * 
     * @return
     *     the new instance of {@link CommentType.Disease }
     */
    public CommentType.Disease createCommentTypeDisease() {
        return new CommentType.Disease();
    }

    /**
     * Create an instance of {@link CommentType.Conflict.Sequence }
     * 
     * @return
     *     the new instance of {@link CommentType.Conflict.Sequence }
     */
    public CommentType.Conflict.Sequence createCommentTypeConflictSequence() {
        return new CommentType.Conflict.Sequence();
    }

    /**
     * Create an instance of {@link OrganismType.Lineage }
     * 
     * @return
     *     the new instance of {@link OrganismType.Lineage }
     */
    public OrganismType.Lineage createOrganismTypeLineage() {
        return new OrganismType.Lineage();
    }

    /**
     * Create an instance of {@link ProteinType.RecommendedName }
     * 
     * @return
     *     the new instance of {@link ProteinType.RecommendedName }
     */
    public ProteinType.RecommendedName createProteinTypeRecommendedName() {
        return new ProteinType.RecommendedName();
    }

    /**
     * Create an instance of {@link ProteinType.AlternativeName }
     * 
     * @return
     *     the new instance of {@link ProteinType.AlternativeName }
     */
    public ProteinType.AlternativeName createProteinTypeAlternativeName() {
        return new ProteinType.AlternativeName();
    }

    /**
     * Create an instance of {@link ProteinType.SubmittedName }
     * 
     * @return
     *     the new instance of {@link ProteinType.SubmittedName }
     */
    public ProteinType.SubmittedName createProteinTypeSubmittedName() {
        return new ProteinType.SubmittedName();
    }

    /**
     * Create an instance of {@link ProteinType.Domain }
     * 
     * @return
     *     the new instance of {@link ProteinType.Domain }
     */
    public ProteinType.Domain createProteinTypeDomain() {
        return new ProteinType.Domain();
    }

    /**
     * Create an instance of {@link ProteinType.Component }
     * 
     * @return
     *     the new instance of {@link ProteinType.Component }
     */
    public ProteinType.Component createProteinTypeComponent() {
        return new ProteinType.Component();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://uniprot.org/uniprot", name = "copyright")
    public JAXBElement<String> createCopyright(String value) {
        return new JAXBElement<>(_Copyright_QNAME, String.class, null, value);
    }

}
