//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbAltSeqDataName",
    "gbAltSeqDataItems"
})
@XmlRootElement(name = "GBAltSeqData")
public class GBAltSeqData {

    @XmlElement(name = "GBAltSeqData_name", required = true)
    protected String gbAltSeqDataName;
    @XmlElement(name = "GBAltSeqData_items")
    protected GBAltSeqDataItems gbAltSeqDataItems;

    /**
     * Gets the value of the gbAltSeqDataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqDataName() {
        return gbAltSeqDataName;
    }

    /**
     * Sets the value of the gbAltSeqDataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqDataName(String value) {
        this.gbAltSeqDataName = value;
    }

    /**
     * Gets the value of the gbAltSeqDataItems property.
     * 
     * @return
     *     possible object is
     *     {@link GBAltSeqDataItems }
     *     
     */
    public GBAltSeqDataItems getGBAltSeqDataItems() {
        return gbAltSeqDataItems;
    }

    /**
     * Sets the value of the gbAltSeqDataItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBAltSeqDataItems }
     *     
     */
    public void setGBAltSeqDataItems(GBAltSeqDataItems value) {
        this.gbAltSeqDataItems = value;
    }

}
