//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbAltSeqItemInterval",
    "gbAltSeqItemIsgap",
    "gbAltSeqItemGapLength",
    "gbAltSeqItemGapType",
    "gbAltSeqItemGapLinkage",
    "gbAltSeqItemGapComment",
    "gbAltSeqItemFirstAccn",
    "gbAltSeqItemLastAccn",
    "gbAltSeqItemValue"
})
@XmlRootElement(name = "GBAltSeqItem")
public class GBAltSeqItem {

    @XmlElement(name = "GBAltSeqItem_interval")
    protected GBAltSeqItemInterval gbAltSeqItemInterval;
    @XmlElement(name = "GBAltSeqItem_isgap")
    protected GBAltSeqItemIsgap gbAltSeqItemIsgap;
    @XmlElement(name = "GBAltSeqItem_gap-length")
    protected String gbAltSeqItemGapLength;
    @XmlElement(name = "GBAltSeqItem_gap-type")
    protected String gbAltSeqItemGapType;
    @XmlElement(name = "GBAltSeqItem_gap-linkage")
    protected String gbAltSeqItemGapLinkage;
    @XmlElement(name = "GBAltSeqItem_gap-comment")
    protected String gbAltSeqItemGapComment;
    @XmlElement(name = "GBAltSeqItem_first-accn")
    protected String gbAltSeqItemFirstAccn;
    @XmlElement(name = "GBAltSeqItem_last-accn")
    protected String gbAltSeqItemLastAccn;
    @XmlElement(name = "GBAltSeqItem_value")
    protected String gbAltSeqItemValue;

    /**
     * Gets the value of the gbAltSeqItemInterval property.
     * 
     * @return
     *     possible object is
     *     {@link GBAltSeqItemInterval }
     *     
     */
    public GBAltSeqItemInterval getGBAltSeqItemInterval() {
        return gbAltSeqItemInterval;
    }

    /**
     * Sets the value of the gbAltSeqItemInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBAltSeqItemInterval }
     *     
     */
    public void setGBAltSeqItemInterval(GBAltSeqItemInterval value) {
        this.gbAltSeqItemInterval = value;
    }

    /**
     * Gets the value of the gbAltSeqItemIsgap property.
     * 
     * @return
     *     possible object is
     *     {@link GBAltSeqItemIsgap }
     *     
     */
    public GBAltSeqItemIsgap getGBAltSeqItemIsgap() {
        return gbAltSeqItemIsgap;
    }

    /**
     * Sets the value of the gbAltSeqItemIsgap property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBAltSeqItemIsgap }
     *     
     */
    public void setGBAltSeqItemIsgap(GBAltSeqItemIsgap value) {
        this.gbAltSeqItemIsgap = value;
    }

    /**
     * Gets the value of the gbAltSeqItemGapLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemGapLength() {
        return gbAltSeqItemGapLength;
    }

    /**
     * Sets the value of the gbAltSeqItemGapLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemGapLength(String value) {
        this.gbAltSeqItemGapLength = value;
    }

    /**
     * Gets the value of the gbAltSeqItemGapType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemGapType() {
        return gbAltSeqItemGapType;
    }

    /**
     * Sets the value of the gbAltSeqItemGapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemGapType(String value) {
        this.gbAltSeqItemGapType = value;
    }

    /**
     * Gets the value of the gbAltSeqItemGapLinkage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemGapLinkage() {
        return gbAltSeqItemGapLinkage;
    }

    /**
     * Sets the value of the gbAltSeqItemGapLinkage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemGapLinkage(String value) {
        this.gbAltSeqItemGapLinkage = value;
    }

    /**
     * Gets the value of the gbAltSeqItemGapComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemGapComment() {
        return gbAltSeqItemGapComment;
    }

    /**
     * Sets the value of the gbAltSeqItemGapComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemGapComment(String value) {
        this.gbAltSeqItemGapComment = value;
    }

    /**
     * Gets the value of the gbAltSeqItemFirstAccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemFirstAccn() {
        return gbAltSeqItemFirstAccn;
    }

    /**
     * Sets the value of the gbAltSeqItemFirstAccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemFirstAccn(String value) {
        this.gbAltSeqItemFirstAccn = value;
    }

    /**
     * Gets the value of the gbAltSeqItemLastAccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemLastAccn() {
        return gbAltSeqItemLastAccn;
    }

    /**
     * Sets the value of the gbAltSeqItemLastAccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemLastAccn(String value) {
        this.gbAltSeqItemLastAccn = value;
    }

    /**
     * Gets the value of the gbAltSeqItemValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBAltSeqItemValue() {
        return gbAltSeqItemValue;
    }

    /**
     * Sets the value of the gbAltSeqItemValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBAltSeqItemValue(String value) {
        this.gbAltSeqItemValue = value;
    }

}
