//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbReferenceReference",
    "gbReferencePosition",
    "gbReferenceAuthors",
    "gbReferenceConsortium",
    "gbReferenceTitle",
    "gbReferenceJournal",
    "gbReferenceXref",
    "gbReferencePubmed",
    "gbReferenceRemark"
})
@XmlRootElement(name = "GBReference")
public class GBReference {

    @XmlElement(name = "GBReference_reference", required = true)
    protected String gbReferenceReference;
    @XmlElement(name = "GBReference_position")
    protected String gbReferencePosition;
    @XmlElement(name = "GBReference_authors")
    protected GBReferenceAuthors gbReferenceAuthors;
    @XmlElement(name = "GBReference_consortium")
    protected String gbReferenceConsortium;
    @XmlElement(name = "GBReference_title")
    protected String gbReferenceTitle;
    @XmlElement(name = "GBReference_journal", required = true)
    protected String gbReferenceJournal;
    @XmlElement(name = "GBReference_xref")
    protected GBReferenceXref gbReferenceXref;
    @XmlElement(name = "GBReference_pubmed")
    protected String gbReferencePubmed;
    @XmlElement(name = "GBReference_remark")
    protected String gbReferenceRemark;

    /**
     * Gets the value of the gbReferenceReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferenceReference() {
        return gbReferenceReference;
    }

    /**
     * Sets the value of the gbReferenceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferenceReference(String value) {
        this.gbReferenceReference = value;
    }

    /**
     * Gets the value of the gbReferencePosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferencePosition() {
        return gbReferencePosition;
    }

    /**
     * Sets the value of the gbReferencePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferencePosition(String value) {
        this.gbReferencePosition = value;
    }

    /**
     * Gets the value of the gbReferenceAuthors property.
     * 
     * @return
     *     possible object is
     *     {@link GBReferenceAuthors }
     *     
     */
    public GBReferenceAuthors getGBReferenceAuthors() {
        return gbReferenceAuthors;
    }

    /**
     * Sets the value of the gbReferenceAuthors property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBReferenceAuthors }
     *     
     */
    public void setGBReferenceAuthors(GBReferenceAuthors value) {
        this.gbReferenceAuthors = value;
    }

    /**
     * Gets the value of the gbReferenceConsortium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferenceConsortium() {
        return gbReferenceConsortium;
    }

    /**
     * Sets the value of the gbReferenceConsortium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferenceConsortium(String value) {
        this.gbReferenceConsortium = value;
    }

    /**
     * Gets the value of the gbReferenceTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferenceTitle() {
        return gbReferenceTitle;
    }

    /**
     * Sets the value of the gbReferenceTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferenceTitle(String value) {
        this.gbReferenceTitle = value;
    }

    /**
     * Gets the value of the gbReferenceJournal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferenceJournal() {
        return gbReferenceJournal;
    }

    /**
     * Sets the value of the gbReferenceJournal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferenceJournal(String value) {
        this.gbReferenceJournal = value;
    }

    /**
     * Gets the value of the gbReferenceXref property.
     * 
     * @return
     *     possible object is
     *     {@link GBReferenceXref }
     *     
     */
    public GBReferenceXref getGBReferenceXref() {
        return gbReferenceXref;
    }

    /**
     * Sets the value of the gbReferenceXref property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBReferenceXref }
     *     
     */
    public void setGBReferenceXref(GBReferenceXref value) {
        this.gbReferenceXref = value;
    }

    /**
     * Gets the value of the gbReferencePubmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferencePubmed() {
        return gbReferencePubmed;
    }

    /**
     * Sets the value of the gbReferencePubmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferencePubmed(String value) {
        this.gbReferencePubmed = value;
    }

    /**
     * Gets the value of the gbReferenceRemark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBReferenceRemark() {
        return gbReferenceRemark;
    }

    /**
     * Sets the value of the gbReferenceRemark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBReferenceRemark(String value) {
        this.gbReferenceRemark = value;
    }

}
