//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbStrucCommentName",
    "gbStrucCommentItems"
})
@XmlRootElement(name = "GBStrucComment")
public class GBStrucComment {

    @XmlElement(name = "GBStrucComment_name")
    protected String gbStrucCommentName;
    @XmlElement(name = "GBStrucComment_items", required = true)
    protected GBStrucCommentItems gbStrucCommentItems;

    /**
     * Gets the value of the gbStrucCommentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBStrucCommentName() {
        return gbStrucCommentName;
    }

    /**
     * Sets the value of the gbStrucCommentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBStrucCommentName(String value) {
        this.gbStrucCommentName = value;
    }

    /**
     * Gets the value of the gbStrucCommentItems property.
     * 
     * @return
     *     possible object is
     *     {@link GBStrucCommentItems }
     *     
     */
    public GBStrucCommentItems getGBStrucCommentItems() {
        return gbStrucCommentItems;
    }

    /**
     * Sets the value of the gbStrucCommentItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBStrucCommentItems }
     *     
     */
    public void setGBStrucCommentItems(GBStrucCommentItems value) {
        this.gbStrucCommentItems = value;
    }

}
