//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbXrefDbname",
    "gbXrefId"
})
@XmlRootElement(name = "GBXref")
public class GBXref {

    @XmlElement(name = "GBXref_dbname", required = true)
    protected String gbXrefDbname;
    @XmlElement(name = "GBXref_id", required = true)
    protected String gbXrefId;

    /**
     * Gets the value of the gbXrefDbname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBXrefDbname() {
        return gbXrefDbname;
    }

    /**
     * Sets the value of the gbXrefDbname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBXrefDbname(String value) {
        this.gbXrefDbname = value;
    }

    /**
     * Gets the value of the gbXrefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBXrefId() {
        return gbXrefId;
    }

    /**
     * Sets the value of the gbXrefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBXrefId(String value) {
        this.gbXrefId = value;
    }

}
