.PHONY:all tests
OUTPUT=tests_results.txt
define compile
	(cd .. && make $(1)) || (echo "$(1)	Compilation Failed" >> ${OUTPUT} && exit 999)
endef

TEST_APPS= addlinearindextobed \
		bam2fastq \
		bam2raster \
		bam2wig \
		bam4deseq01 \
		bamgenscan \
		bamliftover \
		bamrenamechr \
		bamstats01 \
		bamstats04 \
		bamtreepack \
		bamviewgui \
		bedliftover \
		bedrenamechr \
		biostar59647 \
		biostar76892 \
		biostar77288 \
		biostar77828 \
		biostar78285 \
		biostar78400 \
		biostar81455 \
		biostar84452 \
		biostar84786 \
		biostar86363 \
		biostar86480 \
		biostar90204 \
		biostar92368 \
		biostar94573 \
		biostar95652 \
		blast2sam \
		blastmapannots \
		blastn2snp \
		bwamemdigest \
		bwamemnop \
		cmpbamhandler1 \
		cmpbams \
		cmpbamsandbuild \
		cmpbamsxml \
		cnv01 \
		coveragenormalizer \
		deprecated.all \
		deseqcount \
		downsamplevcf \
		evs2bed \
		extendbed \
		fastq2fasta \
		fastqentropy \
		fastqgrep \
		fastqphred64to33 \
		fastqrecordtreepack \
		fastqrevcomp \
		findcorruptedfiles \
		findmyvirus \
		findnewsplicesites \
		fixvarscanmissingheader \
		fixvcf \
		fixvcfformat \
		gcanddepth \
		genomicjaspar \
		genscan \
		groupbygene \
		howmanybamdict \
		illuminadir \
		ilmnfastqstats \
		impactofduplicates \
		kg2bed \
		mapuniprot \
		mergesplittedblast \
		metrics2xml \
		ngsfilesscanner \
		ngsfilessummary \
		noemptyvcf \
		nozerovariationvcf \
		pademptyfastq \
		paintcontext \
		sam2json \
		sam2psl \
		sam2tsv \
		sam4weblogo \
		samextractclip \
		samfindclippedregions \
		samfixcigar \
		samgrep \
		samjs \
		samshortinvert \
		samstats01 \
		scanshortinvert \
		sortvcfoninfo \
		sortvcfonref \
		sortvcfonref2 \
		splitbam \
		splitbam2 \
		splitbytile \
		splitread \
		tview \
		tview.cgi \
		vcf2newick \
		vcf2ps \
		vcf2rdf \
		vcf2sql \
		vcf2xml \
		vcfannobam \
		vcfbed \
		vcfbedjs \
		vcfbigwig \
		vcfbiomart \
		vcfcadd \
		vcfcomm \
		vcfcompare \
		vcfcomparegt \
		vcfconcat \
		vcfcutsamples \
		vcffilterdoid \
		vcffiltergo \
		vcffilterjs \
		vcffilterso \
		vcffixindels \
		vcfgo \
		vcfhead \
		vcfin \
		vcfjaspar \
		vcfliftover \
		vcfmapuniprot \
		vcfmerge \
		vcfmerge2 \
		vcfpolyx \
		vcfpredictions \
		vcfrebase \
		vcfregistry.cgi \
		vcfrenamechr \
		vcfrenamesamples \
		vcfsetdict \
		vcfshuffle \
		vcfsimulator \
		vcfstats \
		vcfstopcodon \
		vcfstripannot \
		vcftabixml \
		vcftail \
		vcftreepack \
		vcftrio \
		vcfucsc \
		vcfvcf \
		vcfviewgui \
		vcfviewgui.exe \
		worldmapgenome 

TEST_APPS = vcfhead

all:tests

tests: ${TEST_APPS}
		


addlinearindextobed:
	$(call compile,$@) && echo "$@"

bam2fastq:
	$(call compile,$@) && echo "$@"

bam2raster:
	$(call compile,$@) && echo "$@"

bam2wig:
	$(call compile,$@) && echo "$@"

bam4deseq01:
	$(call compile,$@) && echo "$@"

bamgenscan:
	$(call compile,$@) && echo "$@"

bamliftover:
	$(call compile,$@) && echo "$@"

bamrenamechr:
	$(call compile,$@) && echo "$@"

bamstats01:
	$(call compile,$@) && echo "$@"

bamstats04:
	$(call compile,$@) && echo "$@"

bamtreepack:
	$(call compile,$@) && echo "$@"

bamviewgui:
	$(call compile,$@) && echo "$@"

bedliftover:
	$(call compile,$@) && echo "$@"

bedrenamechr:
	$(call compile,$@) && echo "$@"

biostar:
	$(call compile,$@) && echo "$@"

biostar59647:
	$(call compile,$@) && echo "$@"

biostar76892:
	$(call compile,$@) && echo "$@"

biostar77288:
	$(call compile,$@) && echo "$@"

biostar77828:
	$(call compile,$@) && echo "$@"

biostar78285:
	$(call compile,$@) && echo "$@"

biostar78400:
	$(call compile,$@) && echo "$@"

biostar81455:
	$(call compile,$@) && echo "$@"

biostar84452:
	$(call compile,$@) && echo "$@"

biostar84786:
	$(call compile,$@) && echo "$@"

biostar86363:
	$(call compile,$@) && echo "$@"

biostar86480:
	$(call compile,$@) && echo "$@"

biostar90204:
	$(call compile,$@) && echo "$@"

biostar92368:
	$(call compile,$@) && echo "$@"

biostar94573:
	$(call compile,$@) && echo "$@"

biostar95652:
	$(call compile,$@) && echo "$@"

blast2sam:
	$(call compile,$@) && echo "$@"

blastfastq:
	$(call compile,$@) && echo "$@"

blastmapannots:
	$(call compile,$@) && echo "$@"

blastn2snp:
	$(call compile,$@) && echo "$@"

bwamemdigest:
	$(call compile,$@) && echo "$@"

bwamemnop:
	$(call compile,$@) && echo "$@"

cmpbamhandler1:
	$(call compile,$@) && echo "$@"

cmpbams:
	$(call compile,$@) && echo "$@"

cmpbamsandbuild:
	$(call compile,$@) && echo "$@"

cmpbamsxml:
	$(call compile,$@) && echo "$@"

cnv01:
	$(call compile,$@) && echo "$@"

coveragenormalizer:
	$(call compile,$@) && echo "$@"

deprecated.all:
	$(call compile,$@) && echo "$@"

deseqcount:
	$(call compile,$@) && echo "$@"

dist/cluster20120920:
	$(call compile,$@) && echo "$@"

dist/cnv20120907.jar:
	$(call compile,$@) && echo "$@"

dist/invert20120917:
	$(call compile,$@) && echo "$@"

downsamplevcf:
	$(call compile,$@) && echo "$@"

evs2bed:
	$(call compile,$@) && echo "$@"

extendbed:
	$(call compile,$@) && echo "$@"

fastq2fasta:
	$(call compile,$@) && echo "$@"

fastqentropy:
	$(call compile,$@) && echo "$@"

fastqgrep:
	$(call compile,$@) && echo "$@"

fastqphred64to33:
	$(call compile,$@) && echo "$@"

fastqrecordtreepack:
	$(call compile,$@) && echo "$@"

fastqrevcomp:
	$(call compile,$@) && echo "$@"

findcorruptedfiles:
	$(call compile,$@) && echo "$@"

findmyvirus:
	$(call compile,$@) && echo "$@"

findnewsplicesites:
	$(call compile,$@) && echo "$@"

fixvarscanmissingheader:
	$(call compile,$@) && echo "$@"

fixvcf:
	$(call compile,$@) && echo "$@"

fixvcfformat:
	$(call compile,$@) && echo "$@"

gcanddepth:
	$(call compile,$@) && echo "$@"

genomicjaspar:
	$(call compile,$@) && echo "$@"

genscan:
	$(call compile,$@) && echo "$@"

groupbygene:
	$(call compile,$@) && echo "$@"

howmanybamdict:
	$(call compile,$@) && echo "$@"

htsjdk:
	$(call compile,$@) && echo "$@"

idea20130924:
	$(call compile,$@) && echo "$@"

illuminadir:
	$(call compile,$@) && echo "$@"

ilmnfastqstats:
	$(call compile,$@) && echo "$@"

impactofduplicates:
	$(call compile,$@) && echo "$@"

jeter:
	$(call compile,$@) && echo "$@"

kg2bed:
	$(call compile,$@) && echo "$@"

mapuniprot:
	$(call compile,$@) && echo "$@"

mergesplittedblast:
	$(call compile,$@) && echo "$@"

metrics2xml:
	$(call compile,$@) && echo "$@"

ngsfilesscanner:
	$(call compile,$@) && echo "$@"

ngsfilessummary:
	$(call compile,$@) && echo "$@"

noemptyvcf:
	$(call compile,$@) && echo "$@"

nozerovariationvcf:
	$(call compile,$@) && echo "$@"

pademptyfastq:
	$(call compile,$@) && echo "$@"

paintcontext:
	$(call compile,$@) && echo "$@"

rmi4ngs:
	$(call compile,$@) && echo "$@"

sam2json:
	$(call compile,$@) && echo "$@"

sam2psl:
	$(call compile,$@) && echo "$@"

sam2tsv:
	$(call compile,$@) && echo "$@"

sam4weblogo:
	$(call compile,$@) && echo "$@"

samextractclip:
	$(call compile,$@) && echo "$@"

samfindclippedregions:
	$(call compile,$@) && echo "$@"

samfixcigar:
	$(call compile,$@) && echo "$@"

samgrep:
	$(call compile,$@) && echo "$@"

samjs:
	$(call compile,$@) && echo "$@"

samshortinvert:
	$(call compile,$@) && echo "$@"

samstats01:
	$(call compile,$@) && echo "$@"

scanshortinvert:
	$(call compile,$@) && echo "$@"

sortvcfoninfo:
	$(call compile,$@) && echo "$@"

sortvcfonref:
	$(call compile,$@) && echo "$@"

sortvcfonref2:
	$(call compile,$@) && echo "$@"

splitbam:
	$(call compile,$@) && echo "$@"

splitbam2:
	$(call compile,$@) && echo "$@"

splitbytile:
	$(call compile,$@) && echo "$@"

splitread:
	$(call compile,$@) && echo "$@"

tview:
	$(call compile,$@) && echo "$@"

tview.cgi:
	$(call compile,$@) && echo "$@"

vcf2newick:
	$(call compile,$@) && echo "$@"

vcf2ps:
	$(call compile,$@) && echo "$@"

vcf2rdf:
	$(call compile,$@) && echo "$@"

vcf2sql:
	$(call compile,$@) && echo "$@"

vcf2xml:
	$(call compile,$@) && echo "$@"

vcfannobam:
	$(call compile,$@) && echo "$@"

vcfbed:
	$(call compile,$@) && echo "$@"

vcfbedjs:
	$(call compile,$@) && echo "$@"

vcfbigwig:
	$(call compile,$@) && echo "$@"

vcfbiomart:
	$(call compile,$@) && echo "$@"

vcfcadd:
	$(call compile,$@) && echo "$@"

vcfcomm:
	$(call compile,$@) && echo "$@"

vcfcompare:
	$(call compile,$@) && echo "$@"

vcfcomparegt:
	$(call compile,$@) && echo "$@"

vcfconcat:
	$(call compile,$@) && echo "$@"

vcfcutsamples:
	$(call compile,$@) && echo "$@"

vcffilterdoid:
	$(call compile,$@) && echo "$@"

vcffiltergo:
	$(call compile,$@) && echo "$@"

vcffilterjs:
	$(call compile,$@) && echo "$@"

vcffilterso:
	$(call compile,$@) && echo "$@"

vcffixindels:
	$(call compile,$@) && echo "$@"

vcfgo:
	$(call compile,$@) && echo "$@"

vcfhead:
	$(call compile,$@) && java -jar ${dist.dir}/$@.jar -n 2 ${htsjdk.home}/testdata/htsjdk/variant/ILLUMINA.wex.broad_phase2_baseline.20111114.both.exome.genotypes.1000.vcf > /dev/null && echo "OK: $@" > $(addsuffix .ok,$@)

vcfin:
	$(call compile,$@) && echo "$@"

vcfjaspar:
	$(call compile,$@) && echo "$@"

vcfliftover:
	$(call compile,$@) && echo "$@"

vcfmapuniprot:
	$(call compile,$@) && echo "$@"

vcfmerge:
	$(call compile,$@) && echo "$@"

vcfmerge2:
	$(call compile,$@) && echo "$@"

vcfpolyx:
	$(call compile,$@) && echo "$@"

vcfpredictions:
	$(call compile,$@) && echo "$@"

vcfrebase:
	$(call compile,$@) && echo "$@"

vcfregistry.cgi:
	$(call compile,$@) && echo "$@"

vcfrenamechr:
	$(call compile,$@) && echo "$@"

vcfrenamesamples:
	$(call compile,$@) && echo "$@"

vcfsetdict:
	$(call compile,$@) && echo "$@"

vcfshuffle:
	$(call compile,$@) && echo "$@"

vcfsimulator:
	$(call compile,$@) && echo "$@"

vcfstats:
	$(call compile,$@) && echo "$@"

vcfstopcodon:
	$(call compile,$@) && echo "$@"

vcfstripannot:
	$(call compile,$@) && echo "$@"

vcftabixml:
	$(call compile,$@) && echo "$@"

vcftail:
	$(call compile,$@) && echo "$@"

vcftreepack:
	$(call compile,$@) && echo "$@"

vcftrio:
	$(call compile,$@) && echo "$@"

vcfucsc:
	$(call compile,$@) && echo "$@"

vcfvcf:
	$(call compile,$@) && echo "$@"

vcfviewgui:
	$(call compile,$@) && echo "$@"

vcfviewgui.exe:
	$(call compile,$@) && echo "$@"

worldmapgenome:
	$(call compile,$@) && echo "$@"

