/* SchemaParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. SchemaParserTokenManager.java */
package com.github.lindenb.jvarkit.sql.parser;
import htsjdk.samtools.util.Locatable;
import com.github.lindenb.jvarkit.io.IOUtils;
import java.util.*;
import java.io.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class SchemaParserTokenManager implements SchemaParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 40;
            return 24;
         }
         if ((active0 & 0x101000000L) != 0L)
         {
            jjmatchedKind = 40;
            return 76;
         }
         if ((active0 & 0x1e88ce38c0L) != 0L)
         {
            jjmatchedKind = 40;
            return 28;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 40;
            return 71;
         }
         if ((active0 & 0x20000300L) != 0L)
         {
            jjmatchedKind = 40;
            return 53;
         }
         if ((active0 & 0x6000420L) != 0L)
         {
            jjmatchedKind = 40;
            return 62;
         }
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 40;
            return 15;
         }
         return -1;
      case 1:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
            return 52;
         }
         if ((active0 & 0x800L) != 0L)
            return 28;
         if ((active0 & 0x1f8fce75e0L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
            return 28;
         }
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
            return 23;
         }
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
            return 14;
         }
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
            return 54;
         }
         return -1;
      case 2:
         if ((active0 & 0x1f8f4c6760L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
            return 28;
         }
         if ((active0 & 0x821080L) != 0L)
            return 28;
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
            return 13;
         }
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
            return 22;
         }
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
            return 51;
         }
         return -1;
      case 3:
         if ((active0 & 0x10000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return 21;
         }
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return 12;
         }
         if ((active0 & 0x178f044740L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return 28;
         }
         if ((active0 & 0x800482020L) != 0L)
            return 28;
         if ((active0 & 0x20000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return 50;
         }
         return -1;
      case 4:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 4;
            return 20;
         }
         if ((active0 & 0x8000100L) != 0L)
            return 28;
         if ((active0 & 0x1fa7244640L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 4;
            return 28;
         }
         return -1;
      case 5:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
            return 19;
         }
         if ((active0 & 0x304004040L) != 0L)
            return 28;
         if ((active0 & 0x1ca3240600L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
            return 28;
         }
         return -1;
      case 6:
         if ((active0 & 0x893200600L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 6;
            return 28;
         }
         if ((active0 & 0x1420040000L) != 0L)
            return 28;
         return -1;
      case 7:
         if ((active0 & 0x83200400L) != 0L)
            return 28;
         if ((active0 & 0x810000200L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 7;
            return 28;
         }
         return -1;
      case 8:
         if ((active0 & 0x800000200L) != 0L)
            return 28;
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 8;
            return 28;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 45);
      case 41:
         return jjStopAtPos(0, 46);
      case 44:
         return jjStopAtPos(0, 47);
      case 59:
         return jjStopAtPos(0, 44);
      case 61:
         return jjStopAtPos(0, 43);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1800080040L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x6000420L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800800L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x3000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x101000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20000300L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x280000080L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2040500L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x10020200L);
      case 70:
      case 102:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(1, 11, 28);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x800080000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x120000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8400000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x280800000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x1004201000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000060L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x801080000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 69:
      case 101:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x600004000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000002000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x20200000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8400020L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
      case 84:
      case 116:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(2, 12, 28);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 28);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000400L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 89:
      case 121:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(2, 17, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000440L);
      case 66:
      case 98:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x90000000L);
      case 76:
      case 108:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x1001000100L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 80:
      case 112:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 5, 28);
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
      case 82:
      case 114:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x1c00000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x200400L);
      case 69:
      case 101:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 28);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x5000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 84:
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 28);
         return jjMoveStringLiteralDfa5_0(active0, 0x2004040L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x210000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x40400L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L);
      case 68:
      case 100:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 28);
         break;
      case 69:
      case 101:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 6, 28);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 28);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 28);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0xa0000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000200L);
      case 83:
      case 115:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 28);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      case 69:
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 36, 28);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 82:
      case 114:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(6, 18, 28);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 84:
      case 116:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(6, 29, 28);
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L);
      case 89:
      case 121:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(6, 34, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(7, 21, 28);
         break;
      case 68:
      case 100:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 31, 28);
         break;
      case 69:
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(7, 10, 28);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 25, 28);
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      case 84:
      case 116:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(7, 24, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000L);
      case 82:
      case 114:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(8, 35, 28);
         break;
      case 89:
      case 121:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(8, 9, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(9, 28, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 78;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 62:
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 39)
                        kind = 39;
                     { jjCheckNAdd(26); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(0, 2); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(3, 5); }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 4;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 0:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if (curChar == 10)
                     kind = 3;
                  break;
               case 4:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(5, 7); }
                  break;
               case 5:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(5, 7); }
                  break;
               case 6:
                  if (curChar == 47 && kind > 4)
                     kind = 4;
                  break;
               case 7:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  { jjCheckNAdd(26); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjAddStates(6, 7); }
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 37:
                  if (curChar == 39)
                     { jjCheckNAddStates(3, 5); }
                  break;
               case 38:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddStates(3, 5); }
                  break;
               case 40:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(3, 5); }
                  break;
               case 41:
                  if (curChar == 39 && kind > 49)
                     kind = 49;
                  break;
               case 42:
                  if (curChar == 34)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 43:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 45:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 46:
                  if (curChar == 34 && kind > 50)
                     kind = 50;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 62:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 19:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 23:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 14:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  else if (curChar == 64)
                     { jjCheckNAddTwoStates(34, 35); }
                  else if (curChar == 96)
                     jjstateSet[jjnewStateCnt++] = 30;
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(8, 9); }
                  else if ((0x2000000020L & l) != 0L)
                     { jjAddStates(10, 11); }
                  else if ((0x1000000010L & l) != 0L)
                     { jjAddStates(12, 13); }
                  else if ((0x10000000100000L & l) != 0L)
                     { jjAddStates(14, 15); }
                  else if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 12:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 53:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  else if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 51:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x200000002000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 76:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x2000000020L & l) != 0L)
                     { jjCheckNAdd(75); }
                  if ((0x2000000020L & l) != 0L)
                     { jjCheckNAdd(75); }
                  break;
               case 24:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 13:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 71:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 54:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(9); }
                  break;
               case 52:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     { jjCheckNAdd(28); }
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 1:
                  { jjAddStates(16, 17); }
                  break;
               case 5:
                  { jjAddStates(18, 19); }
                  break;
               case 9:
                  if ((0x10000000100000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 10:
               case 17:
               case 48:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(9); }
                  break;
               case 11:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 16:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 25:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 27:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 28:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  { jjCheckNAdd(28); }
                  break;
               case 29:
                  if (curChar == 96)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 32:
                  if (curChar == 96 && kind > 41)
                     kind = 41;
                  break;
               case 33:
                  if (curChar == 64)
                     { jjCheckNAddTwoStates(34, 35); }
                  break;
               case 34:
                  if (curChar == 64)
                     { jjCheckNAdd(35); }
                  break;
               case 35:
               case 36:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  { jjCheckNAdd(36); }
                  break;
               case 38:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(3, 5); }
                  break;
               case 39:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x14404410144044L & l) != 0L)
                     { jjCheckNAddStates(3, 5); }
                  break;
               case 43:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 44:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 45:
                  if ((0x14404410144044L & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 47:
                  if ((0x10000000100000L & l) != 0L)
                     { jjAddStates(14, 15); }
                  break;
               case 49:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 55:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x1000000010L & l) != 0L)
                     { jjAddStates(12, 13); }
                  break;
               case 57:
                  if ((0x10000000100000L & l) != 0L && kind > 20)
                     kind = 20;
                  break;
               case 58:
               case 63:
                  if ((0x100000001000L & l) != 0L)
                     { jjCheckNAdd(57); }
                  break;
               case 59:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 64:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(10, 11); }
                  break;
               case 69:
                  if ((0x200000002000L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 70:
               case 72:
                  if ((0x20000000200000L & l) != 0L)
                     { jjCheckNAdd(69); }
                  break;
               case 73:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(8, 9); }
                  break;
               case 75:
                  if ((0x10000000100000L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 77:
                  if ((0x2000000020L & l) != 0L)
                     { jjCheckNAdd(75); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(16, 17); }
                  break;
               case 5:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(18, 19); }
                  break;
               case 38:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(3, 5); }
                  break;
               case 43:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(0, 2); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 78 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, "\75", "\73", "\50", "\51", "\54", null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   43, 44, 46, 38, 39, 41, 31, 32, 76, 77, 71, 73, 62, 67, 53, 55, 
   1, 2, 5, 7, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000400L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public SchemaParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public SchemaParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 78; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, 
};
static final long[] jjtoToken = {
   0x6ff9fffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[78];
    private final int[] jjstateSet = new int[2 * 78];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
