//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdSeqLocus",
    "insdSeqLength",
    "insdSeqStrandedness",
    "insdSeqMoltype",
    "insdSeqTopology",
    "insdSeqDivision",
    "insdSeqUpdateDate",
    "insdSeqCreateDate",
    "insdSeqUpdateRelease",
    "insdSeqCreateRelease",
    "insdSeqDefinition",
    "insdSeqPrimaryAccession",
    "insdSeqEntryVersion",
    "insdSeqAccessionVersion",
    "insdSeqOtherSeqids",
    "insdSeqSecondaryAccessions",
    "insdSeqProject",
    "insdSeqKeywords",
    "insdSeqSegment",
    "insdSeqSource",
    "insdSeqOrganism",
    "insdSeqTaxonomy",
    "insdSeqReferences",
    "insdSeqComment",
    "insdSeqCommentSet",
    "insdSeqStrucComments",
    "insdSeqPrimary",
    "insdSeqSourceDb",
    "insdSeqDatabaseReference",
    "insdSeqFeatureTable",
    "insdSeqFeatureSet",
    "insdSeqSequence",
    "insdSeqContig",
    "insdSeqAltSeq",
    "insdSeqXrefs"
})
@XmlRootElement(name = "INSDSeq")
public class INSDSeq {

    @XmlElement(name = "INSDSeq_locus")
    protected String insdSeqLocus;
    @XmlElement(name = "INSDSeq_length", required = true)
    protected String insdSeqLength;
    @XmlElement(name = "INSDSeq_strandedness")
    protected String insdSeqStrandedness;
    @XmlElement(name = "INSDSeq_moltype", required = true)
    protected String insdSeqMoltype;
    @XmlElement(name = "INSDSeq_topology")
    protected String insdSeqTopology;
    @XmlElement(name = "INSDSeq_division")
    protected String insdSeqDivision;
    @XmlElement(name = "INSDSeq_update-date")
    protected String insdSeqUpdateDate;
    @XmlElement(name = "INSDSeq_create-date")
    protected String insdSeqCreateDate;
    @XmlElement(name = "INSDSeq_update-release")
    protected String insdSeqUpdateRelease;
    @XmlElement(name = "INSDSeq_create-release")
    protected String insdSeqCreateRelease;
    @XmlElement(name = "INSDSeq_definition")
    protected String insdSeqDefinition;
    @XmlElement(name = "INSDSeq_primary-accession")
    protected String insdSeqPrimaryAccession;
    @XmlElement(name = "INSDSeq_entry-version")
    protected String insdSeqEntryVersion;
    @XmlElement(name = "INSDSeq_accession-version")
    protected String insdSeqAccessionVersion;
    @XmlElement(name = "INSDSeq_other-seqids")
    protected INSDSeqOtherSeqids insdSeqOtherSeqids;
    @XmlElement(name = "INSDSeq_secondary-accessions")
    protected INSDSeqSecondaryAccessions insdSeqSecondaryAccessions;
    @XmlElement(name = "INSDSeq_project")
    protected String insdSeqProject;
    @XmlElement(name = "INSDSeq_keywords")
    protected INSDSeqKeywords insdSeqKeywords;
    @XmlElement(name = "INSDSeq_segment")
    protected String insdSeqSegment;
    @XmlElement(name = "INSDSeq_source")
    protected String insdSeqSource;
    @XmlElement(name = "INSDSeq_organism")
    protected String insdSeqOrganism;
    @XmlElement(name = "INSDSeq_taxonomy")
    protected String insdSeqTaxonomy;
    @XmlElement(name = "INSDSeq_references")
    protected INSDSeqReferences insdSeqReferences;
    @XmlElement(name = "INSDSeq_comment")
    protected String insdSeqComment;
    @XmlElement(name = "INSDSeq_comment-set")
    protected INSDSeqCommentSet insdSeqCommentSet;
    @XmlElement(name = "INSDSeq_struc-comments")
    protected INSDSeqStrucComments insdSeqStrucComments;
    @XmlElement(name = "INSDSeq_primary")
    protected String insdSeqPrimary;
    @XmlElement(name = "INSDSeq_source-db")
    protected String insdSeqSourceDb;
    @XmlElement(name = "INSDSeq_database-reference")
    protected String insdSeqDatabaseReference;
    @XmlElement(name = "INSDSeq_feature-table")
    protected INSDSeqFeatureTable insdSeqFeatureTable;
    @XmlElement(name = "INSDSeq_feature-set")
    protected INSDSeqFeatureSet insdSeqFeatureSet;
    @XmlElement(name = "INSDSeq_sequence")
    protected String insdSeqSequence;
    @XmlElement(name = "INSDSeq_contig")
    protected String insdSeqContig;
    @XmlElement(name = "INSDSeq_alt-seq")
    protected INSDSeqAltSeq insdSeqAltSeq;
    @XmlElement(name = "INSDSeq_xrefs")
    protected INSDSeqXrefs insdSeqXrefs;

    /**
     * Gets the value of the insdSeqLocus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqLocus() {
        return insdSeqLocus;
    }

    /**
     * Sets the value of the insdSeqLocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqLocus(String value) {
        this.insdSeqLocus = value;
    }

    /**
     * Gets the value of the insdSeqLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqLength() {
        return insdSeqLength;
    }

    /**
     * Sets the value of the insdSeqLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqLength(String value) {
        this.insdSeqLength = value;
    }

    /**
     * Gets the value of the insdSeqStrandedness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqStrandedness() {
        return insdSeqStrandedness;
    }

    /**
     * Sets the value of the insdSeqStrandedness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqStrandedness(String value) {
        this.insdSeqStrandedness = value;
    }

    /**
     * Gets the value of the insdSeqMoltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqMoltype() {
        return insdSeqMoltype;
    }

    /**
     * Sets the value of the insdSeqMoltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqMoltype(String value) {
        this.insdSeqMoltype = value;
    }

    /**
     * Gets the value of the insdSeqTopology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqTopology() {
        return insdSeqTopology;
    }

    /**
     * Sets the value of the insdSeqTopology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqTopology(String value) {
        this.insdSeqTopology = value;
    }

    /**
     * Gets the value of the insdSeqDivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqDivision() {
        return insdSeqDivision;
    }

    /**
     * Sets the value of the insdSeqDivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqDivision(String value) {
        this.insdSeqDivision = value;
    }

    /**
     * Gets the value of the insdSeqUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqUpdateDate() {
        return insdSeqUpdateDate;
    }

    /**
     * Sets the value of the insdSeqUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqUpdateDate(String value) {
        this.insdSeqUpdateDate = value;
    }

    /**
     * Gets the value of the insdSeqCreateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqCreateDate() {
        return insdSeqCreateDate;
    }

    /**
     * Sets the value of the insdSeqCreateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqCreateDate(String value) {
        this.insdSeqCreateDate = value;
    }

    /**
     * Gets the value of the insdSeqUpdateRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqUpdateRelease() {
        return insdSeqUpdateRelease;
    }

    /**
     * Sets the value of the insdSeqUpdateRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqUpdateRelease(String value) {
        this.insdSeqUpdateRelease = value;
    }

    /**
     * Gets the value of the insdSeqCreateRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqCreateRelease() {
        return insdSeqCreateRelease;
    }

    /**
     * Sets the value of the insdSeqCreateRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqCreateRelease(String value) {
        this.insdSeqCreateRelease = value;
    }

    /**
     * Gets the value of the insdSeqDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqDefinition() {
        return insdSeqDefinition;
    }

    /**
     * Sets the value of the insdSeqDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqDefinition(String value) {
        this.insdSeqDefinition = value;
    }

    /**
     * Gets the value of the insdSeqPrimaryAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqPrimaryAccession() {
        return insdSeqPrimaryAccession;
    }

    /**
     * Sets the value of the insdSeqPrimaryAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqPrimaryAccession(String value) {
        this.insdSeqPrimaryAccession = value;
    }

    /**
     * Gets the value of the insdSeqEntryVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqEntryVersion() {
        return insdSeqEntryVersion;
    }

    /**
     * Sets the value of the insdSeqEntryVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqEntryVersion(String value) {
        this.insdSeqEntryVersion = value;
    }

    /**
     * Gets the value of the insdSeqAccessionVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqAccessionVersion() {
        return insdSeqAccessionVersion;
    }

    /**
     * Sets the value of the insdSeqAccessionVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqAccessionVersion(String value) {
        this.insdSeqAccessionVersion = value;
    }

    /**
     * Gets the value of the insdSeqOtherSeqids property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqOtherSeqids }
     *     
     */
    public INSDSeqOtherSeqids getINSDSeqOtherSeqids() {
        return insdSeqOtherSeqids;
    }

    /**
     * Sets the value of the insdSeqOtherSeqids property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqOtherSeqids }
     *     
     */
    public void setINSDSeqOtherSeqids(INSDSeqOtherSeqids value) {
        this.insdSeqOtherSeqids = value;
    }

    /**
     * Gets the value of the insdSeqSecondaryAccessions property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqSecondaryAccessions }
     *     
     */
    public INSDSeqSecondaryAccessions getINSDSeqSecondaryAccessions() {
        return insdSeqSecondaryAccessions;
    }

    /**
     * Sets the value of the insdSeqSecondaryAccessions property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqSecondaryAccessions }
     *     
     */
    public void setINSDSeqSecondaryAccessions(INSDSeqSecondaryAccessions value) {
        this.insdSeqSecondaryAccessions = value;
    }

    /**
     * Gets the value of the insdSeqProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqProject() {
        return insdSeqProject;
    }

    /**
     * Sets the value of the insdSeqProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqProject(String value) {
        this.insdSeqProject = value;
    }

    /**
     * Gets the value of the insdSeqKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqKeywords }
     *     
     */
    public INSDSeqKeywords getINSDSeqKeywords() {
        return insdSeqKeywords;
    }

    /**
     * Sets the value of the insdSeqKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqKeywords }
     *     
     */
    public void setINSDSeqKeywords(INSDSeqKeywords value) {
        this.insdSeqKeywords = value;
    }

    /**
     * Gets the value of the insdSeqSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqSegment() {
        return insdSeqSegment;
    }

    /**
     * Sets the value of the insdSeqSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqSegment(String value) {
        this.insdSeqSegment = value;
    }

    /**
     * Gets the value of the insdSeqSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqSource() {
        return insdSeqSource;
    }

    /**
     * Sets the value of the insdSeqSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqSource(String value) {
        this.insdSeqSource = value;
    }

    /**
     * Gets the value of the insdSeqOrganism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqOrganism() {
        return insdSeqOrganism;
    }

    /**
     * Sets the value of the insdSeqOrganism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqOrganism(String value) {
        this.insdSeqOrganism = value;
    }

    /**
     * Gets the value of the insdSeqTaxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqTaxonomy() {
        return insdSeqTaxonomy;
    }

    /**
     * Sets the value of the insdSeqTaxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqTaxonomy(String value) {
        this.insdSeqTaxonomy = value;
    }

    /**
     * Gets the value of the insdSeqReferences property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqReferences }
     *     
     */
    public INSDSeqReferences getINSDSeqReferences() {
        return insdSeqReferences;
    }

    /**
     * Sets the value of the insdSeqReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqReferences }
     *     
     */
    public void setINSDSeqReferences(INSDSeqReferences value) {
        this.insdSeqReferences = value;
    }

    /**
     * Gets the value of the insdSeqComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqComment() {
        return insdSeqComment;
    }

    /**
     * Sets the value of the insdSeqComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqComment(String value) {
        this.insdSeqComment = value;
    }

    /**
     * Gets the value of the insdSeqCommentSet property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqCommentSet }
     *     
     */
    public INSDSeqCommentSet getINSDSeqCommentSet() {
        return insdSeqCommentSet;
    }

    /**
     * Sets the value of the insdSeqCommentSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqCommentSet }
     *     
     */
    public void setINSDSeqCommentSet(INSDSeqCommentSet value) {
        this.insdSeqCommentSet = value;
    }

    /**
     * Gets the value of the insdSeqStrucComments property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqStrucComments }
     *     
     */
    public INSDSeqStrucComments getINSDSeqStrucComments() {
        return insdSeqStrucComments;
    }

    /**
     * Sets the value of the insdSeqStrucComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqStrucComments }
     *     
     */
    public void setINSDSeqStrucComments(INSDSeqStrucComments value) {
        this.insdSeqStrucComments = value;
    }

    /**
     * Gets the value of the insdSeqPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqPrimary() {
        return insdSeqPrimary;
    }

    /**
     * Sets the value of the insdSeqPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqPrimary(String value) {
        this.insdSeqPrimary = value;
    }

    /**
     * Gets the value of the insdSeqSourceDb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqSourceDb() {
        return insdSeqSourceDb;
    }

    /**
     * Sets the value of the insdSeqSourceDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqSourceDb(String value) {
        this.insdSeqSourceDb = value;
    }

    /**
     * Gets the value of the insdSeqDatabaseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqDatabaseReference() {
        return insdSeqDatabaseReference;
    }

    /**
     * Sets the value of the insdSeqDatabaseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqDatabaseReference(String value) {
        this.insdSeqDatabaseReference = value;
    }

    /**
     * Gets the value of the insdSeqFeatureTable property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqFeatureTable }
     *     
     */
    public INSDSeqFeatureTable getINSDSeqFeatureTable() {
        return insdSeqFeatureTable;
    }

    /**
     * Sets the value of the insdSeqFeatureTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqFeatureTable }
     *     
     */
    public void setINSDSeqFeatureTable(INSDSeqFeatureTable value) {
        this.insdSeqFeatureTable = value;
    }

    /**
     * Gets the value of the insdSeqFeatureSet property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqFeatureSet }
     *     
     */
    public INSDSeqFeatureSet getINSDSeqFeatureSet() {
        return insdSeqFeatureSet;
    }

    /**
     * Sets the value of the insdSeqFeatureSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqFeatureSet }
     *     
     */
    public void setINSDSeqFeatureSet(INSDSeqFeatureSet value) {
        this.insdSeqFeatureSet = value;
    }

    /**
     * Gets the value of the insdSeqSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqSequence() {
        return insdSeqSequence;
    }

    /**
     * Sets the value of the insdSeqSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqSequence(String value) {
        this.insdSeqSequence = value;
    }

    /**
     * Gets the value of the insdSeqContig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDSeqContig() {
        return insdSeqContig;
    }

    /**
     * Sets the value of the insdSeqContig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDSeqContig(String value) {
        this.insdSeqContig = value;
    }

    /**
     * Gets the value of the insdSeqAltSeq property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqAltSeq }
     *     
     */
    public INSDSeqAltSeq getINSDSeqAltSeq() {
        return insdSeqAltSeq;
    }

    /**
     * Sets the value of the insdSeqAltSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqAltSeq }
     *     
     */
    public void setINSDSeqAltSeq(INSDSeqAltSeq value) {
        this.insdSeqAltSeq = value;
    }

    /**
     * Gets the value of the insdSeqXrefs property.
     * 
     * @return
     *     possible object is
     *     {@link INSDSeqXrefs }
     *     
     */
    public INSDSeqXrefs getINSDSeqXrefs() {
        return insdSeqXrefs;
    }

    /**
     * Sets the value of the insdSeqXrefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDSeqXrefs }
     *     
     */
    public void setINSDSeqXrefs(INSDSeqXrefs value) {
        this.insdSeqXrefs = value;
    }

}
