//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdFeatureSetAnnotSource",
    "insdFeatureSetFeatures"
})
@XmlRootElement(name = "INSDFeatureSet")
public class INSDFeatureSet {

    @XmlElement(name = "INSDFeatureSet_annot-source")
    protected String insdFeatureSetAnnotSource;
    @XmlElement(name = "INSDFeatureSet_features", required = true)
    protected INSDFeatureSetFeatures insdFeatureSetFeatures;

    /**
     * Gets the value of the insdFeatureSetAnnotSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDFeatureSetAnnotSource() {
        return insdFeatureSetAnnotSource;
    }

    /**
     * Sets the value of the insdFeatureSetAnnotSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDFeatureSetAnnotSource(String value) {
        this.insdFeatureSetAnnotSource = value;
    }

    /**
     * Gets the value of the insdFeatureSetFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link INSDFeatureSetFeatures }
     *     
     */
    public INSDFeatureSetFeatures getINSDFeatureSetFeatures() {
        return insdFeatureSetFeatures;
    }

    /**
     * Sets the value of the insdFeatureSetFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDFeatureSetFeatures }
     *     
     */
    public void setINSDFeatureSetFeatures(INSDFeatureSetFeatures value) {
        this.insdFeatureSetFeatures = value;
    }

}
