//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.insdseq;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdAltSeqData"
})
@XmlRootElement(name = "INSDSeq_alt-seq")
public class INSDSeqAltSeq {

    @XmlElement(name = "INSDAltSeqData")
    protected List<INSDAltSeqData> insdAltSeqData;

    /**
     * Gets the value of the insdAltSeqData property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insdAltSeqData property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getINSDAltSeqData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INSDAltSeqData }
     * </p>
     * 
     * 
     * @return
     *     The value of the insdAltSeqData property.
     */
    public List<INSDAltSeqData> getINSDAltSeqData() {
        if (insdAltSeqData == null) {
            insdAltSeqData = new ArrayList<>();
        }
        return this.insdAltSeqData;
    }

}
