//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdInterval"
})
@XmlRootElement(name = "INSDAltSeqItem_interval")
public class INSDAltSeqItemInterval {

    @XmlElement(name = "INSDInterval", required = true)
    protected INSDInterval insdInterval;

    /**
     * Gets the value of the insdInterval property.
     * 
     * @return
     *     possible object is
     *     {@link INSDInterval }
     *     
     */
    public INSDInterval getINSDInterval() {
        return insdInterval;
    }

    /**
     * Sets the value of the insdInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDInterval }
     *     
     */
    public void setINSDInterval(INSDInterval value) {
        this.insdInterval = value;
    }

}
