//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdQualifierName",
    "insdQualifierValue"
})
@XmlRootElement(name = "INSDQualifier")
public class INSDQualifier {

    @XmlElement(name = "INSDQualifier_name", required = true)
    protected String insdQualifierName;
    @XmlElement(name = "INSDQualifier_value")
    protected String insdQualifierValue;

    /**
     * Gets the value of the insdQualifierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDQualifierName() {
        return insdQualifierName;
    }

    /**
     * Sets the value of the insdQualifierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDQualifierName(String value) {
        this.insdQualifierName = value;
    }

    /**
     * Gets the value of the insdQualifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDQualifierValue() {
        return insdQualifierValue;
    }

    /**
     * Sets the value of the insdQualifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDQualifierValue(String value) {
        this.insdQualifierValue = value;
    }

}
