//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.insdseq;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nih.nlm.ncbi.insdseq package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nih.nlm.ncbi.insdseq
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link INSDIntervalInterbp }
     * 
     * @return
     *     the new instance of {@link INSDIntervalInterbp }
     */
    public INSDIntervalInterbp createINSDIntervalInterbp() {
        return new INSDIntervalInterbp();
    }

    /**
     * Create an instance of {@link INSDSeqKeywords }
     * 
     * @return
     *     the new instance of {@link INSDSeqKeywords }
     */
    public INSDSeqKeywords createINSDSeqKeywords() {
        return new INSDSeqKeywords();
    }

    /**
     * Create an instance of {@link INSDKeyword }
     * 
     * @return
     *     the new instance of {@link INSDKeyword }
     */
    public INSDKeyword createINSDKeyword() {
        return new INSDKeyword();
    }

    /**
     * Create an instance of {@link INSDQualifier }
     * 
     * @return
     *     the new instance of {@link INSDQualifier }
     */
    public INSDQualifier createINSDQualifier() {
        return new INSDQualifier();
    }

    /**
     * Create an instance of {@link INSDAltSeqItemIsgap }
     * 
     * @return
     *     the new instance of {@link INSDAltSeqItemIsgap }
     */
    public INSDAltSeqItemIsgap createINSDAltSeqItemIsgap() {
        return new INSDAltSeqItemIsgap();
    }

    /**
     * Create an instance of {@link INSDIntervalIscomp }
     * 
     * @return
     *     the new instance of {@link INSDIntervalIscomp }
     */
    public INSDIntervalIscomp createINSDIntervalIscomp() {
        return new INSDIntervalIscomp();
    }

    /**
     * Create an instance of {@link INSDSecondaryAccn }
     * 
     * @return
     *     the new instance of {@link INSDSecondaryAccn }
     */
    public INSDSecondaryAccn createINSDSecondaryAccn() {
        return new INSDSecondaryAccn();
    }

    /**
     * Create an instance of {@link INSDInterval }
     * 
     * @return
     *     the new instance of {@link INSDInterval }
     */
    public INSDInterval createINSDInterval() {
        return new INSDInterval();
    }

    /**
     * Create an instance of {@link INSDStrucCommentItem }
     * 
     * @return
     *     the new instance of {@link INSDStrucCommentItem }
     */
    public INSDStrucCommentItem createINSDStrucCommentItem() {
        return new INSDStrucCommentItem();
    }

    /**
     * Create an instance of {@link INSDFeatureSet }
     * 
     * @return
     *     the new instance of {@link INSDFeatureSet }
     */
    public INSDFeatureSet createINSDFeatureSet() {
        return new INSDFeatureSet();
    }

    /**
     * Create an instance of {@link INSDFeatureSetFeatures }
     * 
     * @return
     *     the new instance of {@link INSDFeatureSetFeatures }
     */
    public INSDFeatureSetFeatures createINSDFeatureSetFeatures() {
        return new INSDFeatureSetFeatures();
    }

    /**
     * Create an instance of {@link INSDSeq }
     * 
     * @return
     *     the new instance of {@link INSDSeq }
     */
    public INSDSeq createINSDSeq() {
        return new INSDSeq();
    }

    /**
     * Create an instance of {@link INSDSeqOtherSeqids }
     * 
     * @return
     *     the new instance of {@link INSDSeqOtherSeqids }
     */
    public INSDSeqOtherSeqids createINSDSeqOtherSeqids() {
        return new INSDSeqOtherSeqids();
    }

    /**
     * Create an instance of {@link INSDSeqSecondaryAccessions }
     * 
     * @return
     *     the new instance of {@link INSDSeqSecondaryAccessions }
     */
    public INSDSeqSecondaryAccessions createINSDSeqSecondaryAccessions() {
        return new INSDSeqSecondaryAccessions();
    }

    /**
     * Create an instance of {@link INSDSeqReferences }
     * 
     * @return
     *     the new instance of {@link INSDSeqReferences }
     */
    public INSDSeqReferences createINSDSeqReferences() {
        return new INSDSeqReferences();
    }

    /**
     * Create an instance of {@link INSDSeqCommentSet }
     * 
     * @return
     *     the new instance of {@link INSDSeqCommentSet }
     */
    public INSDSeqCommentSet createINSDSeqCommentSet() {
        return new INSDSeqCommentSet();
    }

    /**
     * Create an instance of {@link INSDSeqStrucComments }
     * 
     * @return
     *     the new instance of {@link INSDSeqStrucComments }
     */
    public INSDSeqStrucComments createINSDSeqStrucComments() {
        return new INSDSeqStrucComments();
    }

    /**
     * Create an instance of {@link INSDSeqFeatureTable }
     * 
     * @return
     *     the new instance of {@link INSDSeqFeatureTable }
     */
    public INSDSeqFeatureTable createINSDSeqFeatureTable() {
        return new INSDSeqFeatureTable();
    }

    /**
     * Create an instance of {@link INSDSeqFeatureSet }
     * 
     * @return
     *     the new instance of {@link INSDSeqFeatureSet }
     */
    public INSDSeqFeatureSet createINSDSeqFeatureSet() {
        return new INSDSeqFeatureSet();
    }

    /**
     * Create an instance of {@link INSDSeqAltSeq }
     * 
     * @return
     *     the new instance of {@link INSDSeqAltSeq }
     */
    public INSDSeqAltSeq createINSDSeqAltSeq() {
        return new INSDSeqAltSeq();
    }

    /**
     * Create an instance of {@link INSDSeqXrefs }
     * 
     * @return
     *     the new instance of {@link INSDSeqXrefs }
     */
    public INSDSeqXrefs createINSDSeqXrefs() {
        return new INSDSeqXrefs();
    }

    /**
     * Create an instance of {@link INSDComment }
     * 
     * @return
     *     the new instance of {@link INSDComment }
     */
    public INSDComment createINSDComment() {
        return new INSDComment();
    }

    /**
     * Create an instance of {@link INSDCommentParagraphs }
     * 
     * @return
     *     the new instance of {@link INSDCommentParagraphs }
     */
    public INSDCommentParagraphs createINSDCommentParagraphs() {
        return new INSDCommentParagraphs();
    }

    /**
     * Create an instance of {@link INSDSet }
     * 
     * @return
     *     the new instance of {@link INSDSet }
     */
    public INSDSet createINSDSet() {
        return new INSDSet();
    }

    /**
     * Create an instance of {@link INSDAltSeqDataItems }
     * 
     * @return
     *     the new instance of {@link INSDAltSeqDataItems }
     */
    public INSDAltSeqDataItems createINSDAltSeqDataItems() {
        return new INSDAltSeqDataItems();
    }

    /**
     * Create an instance of {@link INSDAltSeqItem }
     * 
     * @return
     *     the new instance of {@link INSDAltSeqItem }
     */
    public INSDAltSeqItem createINSDAltSeqItem() {
        return new INSDAltSeqItem();
    }

    /**
     * Create an instance of {@link INSDReferenceAuthors }
     * 
     * @return
     *     the new instance of {@link INSDReferenceAuthors }
     */
    public INSDReferenceAuthors createINSDReferenceAuthors() {
        return new INSDReferenceAuthors();
    }

    /**
     * Create an instance of {@link INSDAuthor }
     * 
     * @return
     *     the new instance of {@link INSDAuthor }
     */
    public INSDAuthor createINSDAuthor() {
        return new INSDAuthor();
    }

    /**
     * Create an instance of {@link INSDFeatureQuals }
     * 
     * @return
     *     the new instance of {@link INSDFeatureQuals }
     */
    public INSDFeatureQuals createINSDFeatureQuals() {
        return new INSDFeatureQuals();
    }

    /**
     * Create an instance of {@link INSDReference }
     * 
     * @return
     *     the new instance of {@link INSDReference }
     */
    public INSDReference createINSDReference() {
        return new INSDReference();
    }

    /**
     * Create an instance of {@link INSDStrucComment }
     * 
     * @return
     *     the new instance of {@link INSDStrucComment }
     */
    public INSDStrucComment createINSDStrucComment() {
        return new INSDStrucComment();
    }

    /**
     * Create an instance of {@link INSDStrucCommentItems }
     * 
     * @return
     *     the new instance of {@link INSDStrucCommentItems }
     */
    public INSDStrucCommentItems createINSDStrucCommentItems() {
        return new INSDStrucCommentItems();
    }

    /**
     * Create an instance of {@link INSDFeature }
     * 
     * @return
     *     the new instance of {@link INSDFeature }
     */
    public INSDFeature createINSDFeature() {
        return new INSDFeature();
    }

    /**
     * Create an instance of {@link INSDCommentParagraph }
     * 
     * @return
     *     the new instance of {@link INSDCommentParagraph }
     */
    public INSDCommentParagraph createINSDCommentParagraph() {
        return new INSDCommentParagraph();
    }

    /**
     * Create an instance of {@link INSDFeatureXrefs }
     * 
     * @return
     *     the new instance of {@link INSDFeatureXrefs }
     */
    public INSDFeatureXrefs createINSDFeatureXrefs() {
        return new INSDFeatureXrefs();
    }

    /**
     * Create an instance of {@link INSDXref }
     * 
     * @return
     *     the new instance of {@link INSDXref }
     */
    public INSDXref createINSDXref() {
        return new INSDXref();
    }

    /**
     * Create an instance of {@link INSDFeatureIntervals }
     * 
     * @return
     *     the new instance of {@link INSDFeatureIntervals }
     */
    public INSDFeatureIntervals createINSDFeatureIntervals() {
        return new INSDFeatureIntervals();
    }

    /**
     * Create an instance of {@link INSDFeaturePartial5 }
     * 
     * @return
     *     the new instance of {@link INSDFeaturePartial5 }
     */
    public INSDFeaturePartial5 createINSDFeaturePartial5() {
        return new INSDFeaturePartial5();
    }

    /**
     * Create an instance of {@link INSDFeaturePartial3 }
     * 
     * @return
     *     the new instance of {@link INSDFeaturePartial3 }
     */
    public INSDFeaturePartial3 createINSDFeaturePartial3() {
        return new INSDFeaturePartial3();
    }

    /**
     * Create an instance of {@link INSDReferenceXref }
     * 
     * @return
     *     the new instance of {@link INSDReferenceXref }
     */
    public INSDReferenceXref createINSDReferenceXref() {
        return new INSDReferenceXref();
    }

    /**
     * Create an instance of {@link INSDSeqid }
     * 
     * @return
     *     the new instance of {@link INSDSeqid }
     */
    public INSDSeqid createINSDSeqid() {
        return new INSDSeqid();
    }

    /**
     * Create an instance of {@link INSDAltSeqItemInterval }
     * 
     * @return
     *     the new instance of {@link INSDAltSeqItemInterval }
     */
    public INSDAltSeqItemInterval createINSDAltSeqItemInterval() {
        return new INSDAltSeqItemInterval();
    }

    /**
     * Create an instance of {@link INSDAltSeqData }
     * 
     * @return
     *     the new instance of {@link INSDAltSeqData }
     */
    public INSDAltSeqData createINSDAltSeqData() {
        return new INSDAltSeqData();
    }

}
