//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdAltSeqItemInterval",
    "insdAltSeqItemIsgap",
    "insdAltSeqItemGapLength",
    "insdAltSeqItemGapType",
    "insdAltSeqItemGapLinkage",
    "insdAltSeqItemGapComment",
    "insdAltSeqItemFirstAccn",
    "insdAltSeqItemLastAccn",
    "insdAltSeqItemValue"
})
@XmlRootElement(name = "INSDAltSeqItem")
public class INSDAltSeqItem {

    @XmlElement(name = "INSDAltSeqItem_interval")
    protected INSDAltSeqItemInterval insdAltSeqItemInterval;
    @XmlElement(name = "INSDAltSeqItem_isgap")
    protected INSDAltSeqItemIsgap insdAltSeqItemIsgap;
    @XmlElement(name = "INSDAltSeqItem_gap-length")
    protected String insdAltSeqItemGapLength;
    @XmlElement(name = "INSDAltSeqItem_gap-type")
    protected String insdAltSeqItemGapType;
    @XmlElement(name = "INSDAltSeqItem_gap-linkage")
    protected String insdAltSeqItemGapLinkage;
    @XmlElement(name = "INSDAltSeqItem_gap-comment")
    protected String insdAltSeqItemGapComment;
    @XmlElement(name = "INSDAltSeqItem_first-accn")
    protected String insdAltSeqItemFirstAccn;
    @XmlElement(name = "INSDAltSeqItem_last-accn")
    protected String insdAltSeqItemLastAccn;
    @XmlElement(name = "INSDAltSeqItem_value")
    protected String insdAltSeqItemValue;

    /**
     * Gets the value of the insdAltSeqItemInterval property.
     * 
     * @return
     *     possible object is
     *     {@link INSDAltSeqItemInterval }
     *     
     */
    public INSDAltSeqItemInterval getINSDAltSeqItemInterval() {
        return insdAltSeqItemInterval;
    }

    /**
     * Sets the value of the insdAltSeqItemInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDAltSeqItemInterval }
     *     
     */
    public void setINSDAltSeqItemInterval(INSDAltSeqItemInterval value) {
        this.insdAltSeqItemInterval = value;
    }

    /**
     * Gets the value of the insdAltSeqItemIsgap property.
     * 
     * @return
     *     possible object is
     *     {@link INSDAltSeqItemIsgap }
     *     
     */
    public INSDAltSeqItemIsgap getINSDAltSeqItemIsgap() {
        return insdAltSeqItemIsgap;
    }

    /**
     * Sets the value of the insdAltSeqItemIsgap property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDAltSeqItemIsgap }
     *     
     */
    public void setINSDAltSeqItemIsgap(INSDAltSeqItemIsgap value) {
        this.insdAltSeqItemIsgap = value;
    }

    /**
     * Gets the value of the insdAltSeqItemGapLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemGapLength() {
        return insdAltSeqItemGapLength;
    }

    /**
     * Sets the value of the insdAltSeqItemGapLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemGapLength(String value) {
        this.insdAltSeqItemGapLength = value;
    }

    /**
     * Gets the value of the insdAltSeqItemGapType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemGapType() {
        return insdAltSeqItemGapType;
    }

    /**
     * Sets the value of the insdAltSeqItemGapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemGapType(String value) {
        this.insdAltSeqItemGapType = value;
    }

    /**
     * Gets the value of the insdAltSeqItemGapLinkage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemGapLinkage() {
        return insdAltSeqItemGapLinkage;
    }

    /**
     * Sets the value of the insdAltSeqItemGapLinkage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemGapLinkage(String value) {
        this.insdAltSeqItemGapLinkage = value;
    }

    /**
     * Gets the value of the insdAltSeqItemGapComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemGapComment() {
        return insdAltSeqItemGapComment;
    }

    /**
     * Sets the value of the insdAltSeqItemGapComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemGapComment(String value) {
        this.insdAltSeqItemGapComment = value;
    }

    /**
     * Gets the value of the insdAltSeqItemFirstAccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemFirstAccn() {
        return insdAltSeqItemFirstAccn;
    }

    /**
     * Sets the value of the insdAltSeqItemFirstAccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemFirstAccn(String value) {
        this.insdAltSeqItemFirstAccn = value;
    }

    /**
     * Gets the value of the insdAltSeqItemLastAccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemLastAccn() {
        return insdAltSeqItemLastAccn;
    }

    /**
     * Sets the value of the insdAltSeqItemLastAccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemLastAccn(String value) {
        this.insdAltSeqItemLastAccn = value;
    }

    /**
     * Gets the value of the insdAltSeqItemValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDAltSeqItemValue() {
        return insdAltSeqItemValue;
    }

    /**
     * Sets the value of the insdAltSeqItemValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDAltSeqItemValue(String value) {
        this.insdAltSeqItemValue = value;
    }

}
