//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdStrucCommentName",
    "insdStrucCommentItems"
})
@XmlRootElement(name = "INSDStrucComment")
public class INSDStrucComment {

    @XmlElement(name = "INSDStrucComment_name")
    protected String insdStrucCommentName;
    @XmlElement(name = "INSDStrucComment_items", required = true)
    protected INSDStrucCommentItems insdStrucCommentItems;

    /**
     * Gets the value of the insdStrucCommentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDStrucCommentName() {
        return insdStrucCommentName;
    }

    /**
     * Sets the value of the insdStrucCommentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDStrucCommentName(String value) {
        this.insdStrucCommentName = value;
    }

    /**
     * Gets the value of the insdStrucCommentItems property.
     * 
     * @return
     *     possible object is
     *     {@link INSDStrucCommentItems }
     *     
     */
    public INSDStrucCommentItems getINSDStrucCommentItems() {
        return insdStrucCommentItems;
    }

    /**
     * Sets the value of the insdStrucCommentItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDStrucCommentItems }
     *     
     */
    public void setINSDStrucCommentItems(INSDStrucCommentItems value) {
        this.insdStrucCommentItems = value;
    }

}
