//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.insdseq;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insdIntervalFrom",
    "insdIntervalTo",
    "insdIntervalPoint",
    "insdIntervalIscomp",
    "insdIntervalInterbp",
    "insdIntervalAccession"
})
@XmlRootElement(name = "INSDInterval")
public class INSDInterval {

    @XmlElement(name = "INSDInterval_from")
    protected String insdIntervalFrom;
    @XmlElement(name = "INSDInterval_to")
    protected String insdIntervalTo;
    @XmlElement(name = "INSDInterval_point")
    protected String insdIntervalPoint;
    @XmlElement(name = "INSDInterval_iscomp")
    protected INSDIntervalIscomp insdIntervalIscomp;
    @XmlElement(name = "INSDInterval_interbp")
    protected INSDIntervalInterbp insdIntervalInterbp;
    @XmlElement(name = "INSDInterval_accession", required = true)
    protected String insdIntervalAccession;

    /**
     * Gets the value of the insdIntervalFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDIntervalFrom() {
        return insdIntervalFrom;
    }

    /**
     * Sets the value of the insdIntervalFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDIntervalFrom(String value) {
        this.insdIntervalFrom = value;
    }

    /**
     * Gets the value of the insdIntervalTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDIntervalTo() {
        return insdIntervalTo;
    }

    /**
     * Sets the value of the insdIntervalTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDIntervalTo(String value) {
        this.insdIntervalTo = value;
    }

    /**
     * Gets the value of the insdIntervalPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDIntervalPoint() {
        return insdIntervalPoint;
    }

    /**
     * Sets the value of the insdIntervalPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDIntervalPoint(String value) {
        this.insdIntervalPoint = value;
    }

    /**
     * Gets the value of the insdIntervalIscomp property.
     * 
     * @return
     *     possible object is
     *     {@link INSDIntervalIscomp }
     *     
     */
    public INSDIntervalIscomp getINSDIntervalIscomp() {
        return insdIntervalIscomp;
    }

    /**
     * Sets the value of the insdIntervalIscomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDIntervalIscomp }
     *     
     */
    public void setINSDIntervalIscomp(INSDIntervalIscomp value) {
        this.insdIntervalIscomp = value;
    }

    /**
     * Gets the value of the insdIntervalInterbp property.
     * 
     * @return
     *     possible object is
     *     {@link INSDIntervalInterbp }
     *     
     */
    public INSDIntervalInterbp getINSDIntervalInterbp() {
        return insdIntervalInterbp;
    }

    /**
     * Sets the value of the insdIntervalInterbp property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSDIntervalInterbp }
     *     
     */
    public void setINSDIntervalInterbp(INSDIntervalInterbp value) {
        this.insdIntervalInterbp = value;
    }

    /**
     * Gets the value of the insdIntervalAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSDIntervalAccession() {
        return insdIntervalAccession;
    }

    /**
     * Sets the value of the insdIntervalAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSDIntervalAccession(String value) {
        this.insdIntervalAccession = value;
    }

}
