//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbFeatureSetAnnotSource",
    "gbFeatureSetFeatures"
})
@XmlRootElement(name = "GBFeatureSet")
public class GBFeatureSet {

    @XmlElement(name = "GBFeatureSet_annot-source")
    protected String gbFeatureSetAnnotSource;
    @XmlElement(name = "GBFeatureSet_features", required = true)
    protected GBFeatureSetFeatures gbFeatureSetFeatures;

    /**
     * Gets the value of the gbFeatureSetAnnotSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBFeatureSetAnnotSource() {
        return gbFeatureSetAnnotSource;
    }

    /**
     * Sets the value of the gbFeatureSetAnnotSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBFeatureSetAnnotSource(String value) {
        this.gbFeatureSetAnnotSource = value;
    }

    /**
     * Gets the value of the gbFeatureSetFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link GBFeatureSetFeatures }
     *     
     */
    public GBFeatureSetFeatures getGBFeatureSetFeatures() {
        return gbFeatureSetFeatures;
    }

    /**
     * Sets the value of the gbFeatureSetFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBFeatureSetFeatures }
     *     
     */
    public void setGBFeatureSetFeatures(GBFeatureSetFeatures value) {
        this.gbFeatureSetFeatures = value;
    }

}
