//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbIntervalFrom",
    "gbIntervalTo",
    "gbIntervalPoint",
    "gbIntervalIscomp",
    "gbIntervalInterbp",
    "gbIntervalAccession"
})
@XmlRootElement(name = "GBInterval")
public class GBInterval {

    @XmlElement(name = "GBInterval_from")
    protected String gbIntervalFrom;
    @XmlElement(name = "GBInterval_to")
    protected String gbIntervalTo;
    @XmlElement(name = "GBInterval_point")
    protected String gbIntervalPoint;
    @XmlElement(name = "GBInterval_iscomp")
    protected GBIntervalIscomp gbIntervalIscomp;
    @XmlElement(name = "GBInterval_interbp")
    protected GBIntervalInterbp gbIntervalInterbp;
    @XmlElement(name = "GBInterval_accession", required = true)
    protected String gbIntervalAccession;

    /**
     * Gets the value of the gbIntervalFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBIntervalFrom() {
        return gbIntervalFrom;
    }

    /**
     * Sets the value of the gbIntervalFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBIntervalFrom(String value) {
        this.gbIntervalFrom = value;
    }

    /**
     * Gets the value of the gbIntervalTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBIntervalTo() {
        return gbIntervalTo;
    }

    /**
     * Sets the value of the gbIntervalTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBIntervalTo(String value) {
        this.gbIntervalTo = value;
    }

    /**
     * Gets the value of the gbIntervalPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBIntervalPoint() {
        return gbIntervalPoint;
    }

    /**
     * Sets the value of the gbIntervalPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBIntervalPoint(String value) {
        this.gbIntervalPoint = value;
    }

    /**
     * Gets the value of the gbIntervalIscomp property.
     * 
     * @return
     *     possible object is
     *     {@link GBIntervalIscomp }
     *     
     */
    public GBIntervalIscomp getGBIntervalIscomp() {
        return gbIntervalIscomp;
    }

    /**
     * Sets the value of the gbIntervalIscomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBIntervalIscomp }
     *     
     */
    public void setGBIntervalIscomp(GBIntervalIscomp value) {
        this.gbIntervalIscomp = value;
    }

    /**
     * Gets the value of the gbIntervalInterbp property.
     * 
     * @return
     *     possible object is
     *     {@link GBIntervalInterbp }
     *     
     */
    public GBIntervalInterbp getGBIntervalInterbp() {
        return gbIntervalInterbp;
    }

    /**
     * Sets the value of the gbIntervalInterbp property.
     * 
     * @param value
     *     allowed object is
     *     {@link GBIntervalInterbp }
     *     
     */
    public void setGBIntervalInterbp(GBIntervalInterbp value) {
        this.gbIntervalInterbp = value;
    }

    /**
     * Gets the value of the gbIntervalAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBIntervalAccession() {
        return gbIntervalAccession;
    }

    /**
     * Sets the value of the gbIntervalAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBIntervalAccession(String value) {
        this.gbIntervalAccession = value;
    }

}
