//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.gb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbQualifierName",
    "gbQualifierValue"
})
@XmlRootElement(name = "GBQualifier")
public class GBQualifier {

    @XmlElement(name = "GBQualifier_name", required = true)
    protected String gbQualifierName;
    @XmlElement(name = "GBQualifier_value")
    protected String gbQualifierValue;

    /**
     * Gets the value of the gbQualifierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBQualifierName() {
        return gbQualifierName;
    }

    /**
     * Sets the value of the gbQualifierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBQualifierName(String value) {
        this.gbQualifierName = value;
    }

    /**
     * Gets the value of the gbQualifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGBQualifierValue() {
        return gbQualifierValue;
    }

    /**
     * Sets the value of the gbQualifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGBQualifierValue(String value) {
        this.gbQualifierValue = value;
    }

}
