//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.gb;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gbStrucComment"
})
@XmlRootElement(name = "GBSeq_struc-comments")
public class GBSeqStrucComments {

    @XmlElement(name = "GBStrucComment")
    protected List<GBStrucComment> gbStrucComment;

    /**
     * Gets the value of the gbStrucComment property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gbStrucComment property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getGBStrucComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GBStrucComment }
     * </p>
     * 
     * 
     * @return
     *     The value of the gbStrucComment property.
     */
    public List<GBStrucComment> getGBStrucComment() {
        if (gbStrucComment == null) {
            gbStrucComment = new ArrayList<>();
        }
        return this.gbStrucComment;
    }

}
