//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.github.lindenb.jvarkit.ncbi.schema.blast;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blastOutputProgram",
    "blastOutputVersion",
    "blastOutputReference",
    "blastOutputDb",
    "blastOutputQueryID",
    "blastOutputQueryDef",
    "blastOutputQueryLen",
    "blastOutputQuerySeq",
    "blastOutputParam",
    "blastOutputIterations",
    "blastOutputMbstat"
})
@XmlRootElement(name = "BlastOutput")
public class BlastOutput {

    @XmlElement(name = "BlastOutput_program", required = true)
    protected String blastOutputProgram;
    @XmlElement(name = "BlastOutput_version", required = true)
    protected String blastOutputVersion;
    @XmlElement(name = "BlastOutput_reference", required = true)
    protected String blastOutputReference;
    @XmlElement(name = "BlastOutput_db", required = true)
    protected String blastOutputDb;
    @XmlElement(name = "BlastOutput_query-ID", required = true)
    protected String blastOutputQueryID;
    @XmlElement(name = "BlastOutput_query-def", required = true)
    protected String blastOutputQueryDef;
    @XmlElement(name = "BlastOutput_query-len", required = true)
    protected String blastOutputQueryLen;
    @XmlElement(name = "BlastOutput_query-seq")
    protected String blastOutputQuerySeq;
    @XmlElement(name = "BlastOutput_param", required = true)
    protected BlastOutputParam blastOutputParam;
    @XmlElement(name = "BlastOutput_iterations", required = true)
    protected BlastOutputIterations blastOutputIterations;
    @XmlElement(name = "BlastOutput_mbstat")
    protected BlastOutputMbstat blastOutputMbstat;

    /**
     * Gets the value of the blastOutputProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputProgram() {
        return blastOutputProgram;
    }

    /**
     * Sets the value of the blastOutputProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputProgram(String value) {
        this.blastOutputProgram = value;
    }

    /**
     * Gets the value of the blastOutputVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputVersion() {
        return blastOutputVersion;
    }

    /**
     * Sets the value of the blastOutputVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputVersion(String value) {
        this.blastOutputVersion = value;
    }

    /**
     * Gets the value of the blastOutputReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputReference() {
        return blastOutputReference;
    }

    /**
     * Sets the value of the blastOutputReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputReference(String value) {
        this.blastOutputReference = value;
    }

    /**
     * Gets the value of the blastOutputDb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputDb() {
        return blastOutputDb;
    }

    /**
     * Sets the value of the blastOutputDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputDb(String value) {
        this.blastOutputDb = value;
    }

    /**
     * Gets the value of the blastOutputQueryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputQueryID() {
        return blastOutputQueryID;
    }

    /**
     * Sets the value of the blastOutputQueryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputQueryID(String value) {
        this.blastOutputQueryID = value;
    }

    /**
     * Gets the value of the blastOutputQueryDef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputQueryDef() {
        return blastOutputQueryDef;
    }

    /**
     * Sets the value of the blastOutputQueryDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputQueryDef(String value) {
        this.blastOutputQueryDef = value;
    }

    /**
     * Gets the value of the blastOutputQueryLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputQueryLen() {
        return blastOutputQueryLen;
    }

    /**
     * Sets the value of the blastOutputQueryLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputQueryLen(String value) {
        this.blastOutputQueryLen = value;
    }

    /**
     * Gets the value of the blastOutputQuerySeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlastOutputQuerySeq() {
        return blastOutputQuerySeq;
    }

    /**
     * Sets the value of the blastOutputQuerySeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlastOutputQuerySeq(String value) {
        this.blastOutputQuerySeq = value;
    }

    /**
     * Gets the value of the blastOutputParam property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputParam }
     *     
     */
    public BlastOutputParam getBlastOutputParam() {
        return blastOutputParam;
    }

    /**
     * Sets the value of the blastOutputParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputParam }
     *     
     */
    public void setBlastOutputParam(BlastOutputParam value) {
        this.blastOutputParam = value;
    }

    /**
     * Gets the value of the blastOutputIterations property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputIterations }
     *     
     */
    public BlastOutputIterations getBlastOutputIterations() {
        return blastOutputIterations;
    }

    /**
     * Sets the value of the blastOutputIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputIterations }
     *     
     */
    public void setBlastOutputIterations(BlastOutputIterations value) {
        this.blastOutputIterations = value;
    }

    /**
     * Gets the value of the blastOutputMbstat property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputMbstat }
     *     
     */
    public BlastOutputMbstat getBlastOutputMbstat() {
        return blastOutputMbstat;
    }

    /**
     * Sets the value of the blastOutputMbstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputMbstat }
     *     
     */
    public void setBlastOutputMbstat(BlastOutputMbstat value) {
        this.blastOutputMbstat = value;
    }

}
