//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.nih.nlm.ncbi.blast;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hspNum",
    "hspBitScore",
    "hspScore",
    "hspEvalue",
    "hspQueryFrom",
    "hspQueryTo",
    "hspHitFrom",
    "hspHitTo",
    "hspPatternFrom",
    "hspPatternTo",
    "hspQueryFrame",
    "hspHitFrame",
    "hspIdentity",
    "hspPositive",
    "hspGaps",
    "hspAlignLen",
    "hspDensity",
    "hspQseq",
    "hspHseq",
    "hspMidline"
})
@XmlRootElement(name = "Hsp")
public class Hsp {

    @XmlElement(name = "Hsp_num", required = true)
    protected String hspNum;
    @XmlElement(name = "Hsp_bit-score", required = true)
    protected String hspBitScore;
    @XmlElement(name = "Hsp_score", required = true)
    protected String hspScore;
    @XmlElement(name = "Hsp_evalue", required = true)
    protected String hspEvalue;
    @XmlElement(name = "Hsp_query-from", required = true)
    protected String hspQueryFrom;
    @XmlElement(name = "Hsp_query-to", required = true)
    protected String hspQueryTo;
    @XmlElement(name = "Hsp_hit-from", required = true)
    protected String hspHitFrom;
    @XmlElement(name = "Hsp_hit-to", required = true)
    protected String hspHitTo;
    @XmlElement(name = "Hsp_pattern-from")
    protected String hspPatternFrom;
    @XmlElement(name = "Hsp_pattern-to")
    protected String hspPatternTo;
    @XmlElement(name = "Hsp_query-frame")
    protected String hspQueryFrame;
    @XmlElement(name = "Hsp_hit-frame")
    protected String hspHitFrame;
    @XmlElement(name = "Hsp_identity")
    protected String hspIdentity;
    @XmlElement(name = "Hsp_positive")
    protected String hspPositive;
    @XmlElement(name = "Hsp_gaps")
    protected String hspGaps;
    @XmlElement(name = "Hsp_align-len")
    protected String hspAlignLen;
    @XmlElement(name = "Hsp_density")
    protected String hspDensity;
    @XmlElement(name = "Hsp_qseq", required = true)
    protected String hspQseq;
    @XmlElement(name = "Hsp_hseq", required = true)
    protected String hspHseq;
    @XmlElement(name = "Hsp_midline")
    protected String hspMidline;

    /**
     * Gets the value of the hspNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspNum() {
        return hspNum;
    }

    /**
     * Sets the value of the hspNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspNum(String value) {
        this.hspNum = value;
    }

    /**
     * Gets the value of the hspBitScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspBitScore() {
        return hspBitScore;
    }

    /**
     * Sets the value of the hspBitScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspBitScore(String value) {
        this.hspBitScore = value;
    }

    /**
     * Gets the value of the hspScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspScore() {
        return hspScore;
    }

    /**
     * Sets the value of the hspScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspScore(String value) {
        this.hspScore = value;
    }

    /**
     * Gets the value of the hspEvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspEvalue() {
        return hspEvalue;
    }

    /**
     * Sets the value of the hspEvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspEvalue(String value) {
        this.hspEvalue = value;
    }

    /**
     * Gets the value of the hspQueryFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspQueryFrom() {
        return hspQueryFrom;
    }

    /**
     * Sets the value of the hspQueryFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspQueryFrom(String value) {
        this.hspQueryFrom = value;
    }

    /**
     * Gets the value of the hspQueryTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspQueryTo() {
        return hspQueryTo;
    }

    /**
     * Sets the value of the hspQueryTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspQueryTo(String value) {
        this.hspQueryTo = value;
    }

    /**
     * Gets the value of the hspHitFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspHitFrom() {
        return hspHitFrom;
    }

    /**
     * Sets the value of the hspHitFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspHitFrom(String value) {
        this.hspHitFrom = value;
    }

    /**
     * Gets the value of the hspHitTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspHitTo() {
        return hspHitTo;
    }

    /**
     * Sets the value of the hspHitTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspHitTo(String value) {
        this.hspHitTo = value;
    }

    /**
     * Gets the value of the hspPatternFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspPatternFrom() {
        return hspPatternFrom;
    }

    /**
     * Sets the value of the hspPatternFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspPatternFrom(String value) {
        this.hspPatternFrom = value;
    }

    /**
     * Gets the value of the hspPatternTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspPatternTo() {
        return hspPatternTo;
    }

    /**
     * Sets the value of the hspPatternTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspPatternTo(String value) {
        this.hspPatternTo = value;
    }

    /**
     * Gets the value of the hspQueryFrame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspQueryFrame() {
        return hspQueryFrame;
    }

    /**
     * Sets the value of the hspQueryFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspQueryFrame(String value) {
        this.hspQueryFrame = value;
    }

    /**
     * Gets the value of the hspHitFrame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspHitFrame() {
        return hspHitFrame;
    }

    /**
     * Sets the value of the hspHitFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspHitFrame(String value) {
        this.hspHitFrame = value;
    }

    /**
     * Gets the value of the hspIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspIdentity() {
        return hspIdentity;
    }

    /**
     * Sets the value of the hspIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspIdentity(String value) {
        this.hspIdentity = value;
    }

    /**
     * Gets the value of the hspPositive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspPositive() {
        return hspPositive;
    }

    /**
     * Sets the value of the hspPositive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspPositive(String value) {
        this.hspPositive = value;
    }

    /**
     * Gets the value of the hspGaps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspGaps() {
        return hspGaps;
    }

    /**
     * Sets the value of the hspGaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspGaps(String value) {
        this.hspGaps = value;
    }

    /**
     * Gets the value of the hspAlignLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspAlignLen() {
        return hspAlignLen;
    }

    /**
     * Sets the value of the hspAlignLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspAlignLen(String value) {
        this.hspAlignLen = value;
    }

    /**
     * Gets the value of the hspDensity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspDensity() {
        return hspDensity;
    }

    /**
     * Sets the value of the hspDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspDensity(String value) {
        this.hspDensity = value;
    }

    /**
     * Gets the value of the hspQseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspQseq() {
        return hspQseq;
    }

    /**
     * Sets the value of the hspQseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspQseq(String value) {
        this.hspQseq = value;
    }

    /**
     * Gets the value of the hspHseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspHseq() {
        return hspHseq;
    }

    /**
     * Sets the value of the hspHseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspHseq(String value) {
        this.hspHseq = value;
    }

    /**
     * Gets the value of the hspMidline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHspMidline() {
        return hspMidline;
    }

    /**
     * Sets the value of the hspMidline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHspMidline(String value) {
        this.hspMidline = value;
    }

}
